#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska källtexterna (hämtade server-side
via ExecuteWixAPI mot skarpa V3, ?fields=PLAIN_DESCRIPTION).

☠️ FILEN ÄR EN AVSKRIFT och får därför inte litas på. Kör kontrollen mot
skarpa V3 (samma anrop som ingen skrivning) innan en enda grind körs — samma
ordning som N26–N37. Det är SUMMAN som avgör, inte längden.

Ingen av rundans åtta källtexter bär ett artikelnummer, så ingen rad är
redigerad och summan räknas på texten precis som den står i Wix.
"""
import io, json, collections

K = collections.OrderedDict()

SPEC = '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> '
F = '<li><p><span style="font-weight: 700">'

K["a9360e2a"] = (
 '<p>Entdecken Sie den Schwebebalken für Zuhause– das ideale Trainingsgerät für jedes Niveau! Mit einem'
 ' hochwertigen EVA-Schaumkern und einer eleganten Oberfläche bietet dieser leichte, aber stabilen'
 ' Schwebebalken optimalen Komfort. Die 10 cm breite Wettkampffläche ermöglicht es Ihnen, mühelos Übungen'
 ' wie Handstände, Radschläge und Sprünge zu perfektionieren – ganz bequem zu Hause oder in der Turnhalle.'
 ' Der rutschfeste Boden sorgt für zusätzliche Stabilität.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Faltet sich zur einfachen, kompakten Aufbewahrung in der Mitte zusammen</p></li>'
 '<li><p>✔ 100 % EVA Schaumstoffkern des Schwebebalkens für ein leichtes, komfortables Erlebnis</p></li>'
 '<li><p>✔ 10 cm Wettkampfbreite, Oberfläche des Schwebebalkens fördert präzises Training</p></li>'
 '<li><p>✔ Rutschfester Boden mit 15 cm Breite sorgt für erhöhte Stabilität</p></li>'
 '<li><p>✔ Klettverschluss richtet den gesamten Balken aus, wenn in Gebrauch</p></li>'
 '<li><p>✔ Keine Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Blau</p></li>'
 '<li><p>✔ Material: EVA, Kunststoff, Oxford-Polyester</p></li>'
 '<li><p>✔ Gesamtabmessungen: 236L x 10/15B x 6,5H cm</p></li>'
 '<li><p>✔ Klappmaß: 120L x 15B x 13H cm</p></li>'
 '<li><p>✔ Zugelassenes/Empfohlenes Alter: 3+ Jahre</p></li>'
 '<li><p>✔ Belastbarkeit: 80 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Schwebebalken</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '236L x 15B x 6,5H cm</p></li>'
 + F + 'Färg:</span> Blau</p></li>'
 + F + 'Material:</span> Kunststoff/Polyester</p></li>'
 + F + 'Vikt:</span> 1,6 kg</p></li>'
 + F + 'Paketmått:</span> 119,5 × 14,5 × 16,5 cm</p></li></ul>'
)

K["c694dcaa"] = (
 '<p>Unsere Stehleuchte mit Metall-Stativdesign und Lampenschirm aus Stoff ist eine klassische und elegante'
 ' Dekoration und wird Ihnen einen ruhigen und schönen Abend bescheren. Passt zu fast jedem Dekor in Ihrem'
 ' Zuhause, perfekt für Büro, Bar, Club, Café, Hotel und Restaurant. Stromkabellänge 3m erweitert den'
 ' Einsatzbereich gut. Der Zugschalter unter dem Lampenschirm bringt ein Retro-Gefühl.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Ideal für Büro, Bar, Club, Cafe, Hotel und Restaurant</p></li>'
 '<li><p>✔ Dreieckige Fußkonstruktion für stabilen Stand</p></li>'
 '<li><p>✔ Netzkabellänge 3m erweitert den Einsatzbereich gut</p></li>'
 '<li><p>✔ Ziehen Sie den Schalter unter dem Lampenschirm zum bequemen Ein- und Ausschalten</p></li>'
 '<li><p>✔ Lampensockel E27 (Glühbirne nicht enthalten)</p></li>'
 '<li><p>✔ Einfache Montage</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz, Weiß</p></li>'
 '<li><p>✔ Material: Metall, PS-Platte, Polyester, Baumwolle</p></li>'
 '<li><p>✔ Gesamtmaße: ø37 x 152H cm</p></li>'
 '<li><p>✔ Lampenschirmsmaße: ø37 x 24H cm</p></li>'
 '<li><p>✔ Lampenmastdurchmesser: 1,6 cm</p></li>'
 '<li><p>✔ Stromkabellänge: 3 m</p></li>'
 '<li><p>✔ Eingangsspannung: 230V/50Hz</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Stehlampe</p></li>'
 '<li><p>✔ 1 x Installationsanleitung</p></li></ul>'
 + SPEC + 'ø37cm x 152cm</p></li>'
 + F + 'Färg:</span> Blau, Orange, Gelb</p></li>'
 + F + 'Material:</span> Legierter Stahl/Polyester/Baumwolle/Metall</p></li>'
 + F + 'Vikt:</span> 2,4 kg</p></li>'
 + F + 'Paketmått:</span> 44 × 44 × 14 cm</p></li></ul>'
)

K["d3655c3e"] = (
 '<p>Organisieren Sie Ihre Wäsche und halten Sie Ihr Zuhause mit dem Wäscheregal ordentlich. Dieses verfügt'
 ' über zwei Stoffkörbe zum einfachen Trennen von heller und dunkler Kleidung, jeder mit 17,7 L Kapazität.'
 ' Zwei Regalebenen bieten extra Platz für Haushaltsartikel. Die herausnehmbaren Taschen erleichtern die'
 ' Pflege. Der bemalte Bambusrahmen macht das Regal zu einem eleganten Möbelstück in jedem Schlafzimmer,'
 ' Badezimmer oder Wäscheraum.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Zwei 17,7 L Stoffkörbe helfen dabei, helle und dunkle Kleidung zu sortieren</p></li>'
 '<li><p>✔ Zweistöckige Regale bieten zusätzlichen Stauraum</p></li>'
 '<li><p>✔ Herausziehbare und abnehmbare Einsätze für einfaches Wäschemanagement</p></li>'
 '<li><p>✔ Lackierter Bambusrahmen bietet ein stilvolles, stabiles Design</p></li>'
 '<li><p>✔ 2 Seitenhandgriffe für einfache Bewegung</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Naturholz-Finish, Grau</p></li>'
 '<li><p>✔ Materialien: Bambus, Leinenartiger Stoff (100% Polyester)</p></li>'
 '<li><p>✔ Gesamtabmessungen: 44B x 34T x 96H cm</p></li>'
 '<li><p>✔ Stoffkorb-Größe: 34B x 26T x 20H cm</p></li>'
 '<li><p>✔ Regalgröße: 40B x 34T x 9,5/22,5H cm (oben/mittig)</p></li>'
 '<li><p>✔ Sockelhöhe: (zum Boden) 6 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 14 kg (gesamt), 4 kg (Regal), 3 kg (pro Korb)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Wäscheregal</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '44L x 34B x 96H cm</p></li>'
 + F + 'Färg:</span> Naturholz</p></li>'
 + F + 'Material:</span> Polyester</p></li>'
 + F + 'Vikt:</span> 5 kg</p></li>'
 + F + 'Paketmått:</span> 103 × 38 × 10 cm</p></li></ul>'
)

K["e514191b"] = (
 '<p>Entdecken Sie die perfekte Lösung für flexible Wohnräume mit unserem Blumenregal. Ideal für Mieter, die'
 ' oft umziehen, bietet dieses Regal aus pulverbeschichtetem Metall nicht nur Wetterbeständigkeit, sondern'
 ' auch bemerkenswerte Robustheit. Nutzen Sie es, um Pflanzen, Schuhe oder Badezimmerutensilien stilvoll zu'
 ' organisieren. Die eleganten Verzierungen machen es zu einem echten Blickfang, der jedem Raum eine'
 ' dekorative Note verleiht. Ein Must-have für kleine Räume, das Funktionalität und Ästhetik vereint und sich'
 ' mühelos transportieren lässt.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Hochwertiges Regal aus pulverbeschichtetem Metall</p></li>'
 '<li><p>✔ 4 Böden bieten ausreichend Stauraum für Pflanzen, Schuhe oder Handtücher</p></li>'
 '<li><p>✔ 4 Metallfüße für einen sicheren Stand</p></li>'
 '<li><p>✔ Mit formschönen Blumenverzierungen</p></li>'
 '<li><p>✔ Einfache Montage</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Material: Metall</p></li>'
 '<li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Gewicht: 5,2 kg</p></li>'
 '<li><p>✔ Gesamtmaße: L59,5 x B30 x H92 cm</p></li>'
 '<li><p>✔ Höhe pro Fach: 18,5 cm</p></li>'
 '<li><p>✔ max. Belastbarkeit: 15 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Schuhregal</p></li>'
 '<li><p>✔ 1 x Montageanleitung</p></li></ul>'
 + SPEC + 'L59,5 x B30 x H92 cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 5,9 kg</p></li>'
 + F + 'Paketmått:</span> 94 × 31 × 9 cm</p></li></ul>'
)

K["f75a8a17"] = (
 '<p>Verleihen Sie jeder Ecke neuen Glanz mit dem Blumenständer! Diese dreistufige, fächerförmige Blumentreppe'
 ' passt ideal in Ecken und optimiert jeden Raum, während Ihre Pflanzen reichlich Sonnenlicht erhalten. Dank'
 ' seines durchlüfteten, hohlen Designs und der rostfreien Beschichtung ist die Pflanzentreppe ideal für'
 ' drinnen und draußen geeignet, mit einer Belastbarkeit von bis zu 30 kg. Präsentieren Sie Pflanzen, Bücher'
 ' oder Dekorationsartikel von ihrer besten Seite!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dreistufiges Regal des Blumenständers maximiert die Pflanzenpräsentation in kompakten Räumen</p></li>'
 '<li><p>✔ Das 90° Design des Pflanzenständers passt optimal in jede Ecke</p></li>'
 '<li><p>✔ Hohle Regalböden gewährleisten eine effektive Belüftung</p></li>'
 '<li><p>✔ Aus pulverbeschichtetem Metall gefertigt, für Rostbeständigkeit</p></li>'
 '<li><p>✔ Der fächerförmige Pflanzenständer ergänzt verschiedene Einrichtungsstile</p></li>'
 '<li><p>✔ Vielseitig einsetzbar für Gärten, Balkone, zum Ausstellen von Büchern und Dekorationsartikeln</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 87L x 60B x 60H cm</p></li>'
 '<li><p>✔ Regalgröße: 85B x 20T cm, 56B x 20T cm, 28B x 20T cm</p></li>'
 '<li><p>✔ Regalhöhe zum Boden: 60 cm, 40 cm, 20 cm (oben nach unten)</p></li>'
 '<li><p>✔ Max. Belastung: 30 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Pflanzenständer</p></li>'
 '<li><p>✔ 1 x Gebrauchsanleitung</p></li></ul>'
 + SPEC + '87L x 60B x 60H cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 4 kg</p></li>'
 + F + 'Paketmått:</span> 90 × 40 × 12,5 cm</p></li></ul>'
)

K["ba454107"] = (
 '<p>Verleihen Sie Ihrem Zuhause einen Hauch von Eleganz und Gemütlichkeit mit dem Hocker. Ob als Fußhocker'
 ' oder zusätzliche Sitzgelegenheit – dieser Sitzhocker überzeugt durch seine weiche Polsterung und das'
 ' luxuriöse Obermaterial in Kaschmir-Optik. Perfekt als Akzentsessel in einer Zimmerecke oder als bequeme'
 ' Sitzgelegenheit für Gäste. Machen Sie es sich gemütlich und genießen Sie stilvollen Komfort mit dem'
 ' Hocker.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Auffälliger, stilvoller Look passt gut zu modernen Möbeln</p></li>'
 '<li><p>✔ Dieser multifunktionale Hocker kann als Fußstütze, Hocker oder als zusätzliche Sitzgelegenheit'
 ' dienen</p></li>'
 '<li><p>✔ Der gepolsterte Sitz und der weiche Stoff des Sitzhockers in Kaschmir-Optik bieten'
 ' außergewöhnlichen Komfort und Entspannung</p></li>'
 '<li><p>✔ Glatte Stahlbeine des Hockers mit Pulverbeschichtung für Stabilität und Langlebigkeit</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Dunkelgrau</p></li>'
 '<li><p>✔ Material: Polyester, Stahl</p></li>'
 '<li><p>✔ Gesamtabmessungen: 42L x 42B x 44H cm</p></li>'
 '<li><p>✔ Dicke des Sitzkissens: 10 cm</p></li>'
 '<li><p>✔ Höhe der Beine: 34,5 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Fußhocker</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '42L x 42B x 44H cm</p></li>'
 + F + 'Färg:</span> Dunkelgrau</p></li>'
 + F + 'Material:</span> Polyester, Stahl</p></li>'
 + F + 'Vikt:</span> 4,5 kg</p></li>'
 + F + 'Paketmått:</span> 44 × 14 × 54 cm</p></li></ul>'
)

K["f4bdb64c"] = (
 '<p>Das Pilates Reformer Set macht jeden Raum zum privaten Fitnessstudio: 4 Trainingsmodi ermöglichen'
 ' vielseitige Ganzkörperübungen. Dank klappbarem Design lässt sich das Set platzsparend unter Bett oder Sofa'
 ' verstauen – ideal für Wohnungen. Mit stabiler, rutschfester Basis und umfangreichem Zubehör bietet es ein'
 ' komfortables, sicheres Workout und ist sofort einsatzbereit.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Genießen Sie 5-in-1 Formen für verschiedene Trainingsbewegungen, darunter Liegestütze,'
 ' Bauch-Slides, Plank-Unterstützung, Pilates-Core-Training und unterstützte Kniebeugen</p></li>'
 '<li><p>✔ Trainieren Sie verschiedene Muskelgruppen für Formung, Fettabbau und allgemeine'
 ' Fitnessverbesserung</p></li>'
 '<li><p>✔ Kompakt designt für Wohnungen, kleine Räume und Home-Gyms</p></li>'
 '<li><p>✔ Mit einem faltbaren Design, das auf 49 x 30 x 6 cm zusammenklappbar ist, für einfache'
 ' Lagerung</p></li>'
 '<li><p>✔ Enthält ein Pilates-Board mit Handyhalter, zwei Widerstandsbänder, zwei Ellenbogenpads, eine'
 ' Kniepad, zwei Liegestützgriffe und eine Stange</p></li>'
 '<li><p>✔ Hergestellt aus Kunststoff mit Anti-Rutsch-Pads, sicher bis zu 150 kg belastbar</p></li>'
 '<li><p>✔ Keine Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Hellblau</p></li>'
 '<li><p>✔ Material: Kunststoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 97L x 30B x 3H cm</p></li>'
 '<li><p>✔ Faltmaße: 49L x 30B x 6H cm</p></li>'
 '<li><p>✔ Griff­länge: 12 cm</p></li>'
 '<li><p>✔ Abstand zwischen den Griffen: 22 cm</p></li>'
 '<li><p>✔ Ellbogenpolster Maße: Ø14 cm</p></li>'
 '<li><p>✔ Gleitstrecke: 65 cm</p></li>'
 '<li><p>✔ Liegestützgriff Maße: 16L x 6B cm</p></li>'
 '<li><p>✔ Bandlänge: 58 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 150 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Pilates-Board</p></li>'
 '<li><p>✔ 2 x Widerstandsband</p></li>'
 '<li><p>✔ 2 x Ellbogenpolster</p></li>'
 '<li><p>✔ 1 x Kniepolster</p></li>'
 '<li><p>✔ 2 x Liegestützgriff</p></li>'
 '<li><p>✔ 1 x Stange</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '97L x 30B x 3H cm</p></li>'
 + F + 'Färg:</span> Hellblau</p></li>'
 + F + 'Material:</span> Polypropylen (PP)</p></li>'
 + F + 'Vikt:</span> 3,5 kg</p></li>'
 + F + 'Paketmått:</span> 52,5 × 37,5 × 14,5 cm</p></li></ul>'
)

K["95b6f5bd"] = (
 '<p>Optimieren Sie Ihre Wäscheroutine mit dem Wäschekorb mit Ablage! Dieser stilvolle Schmutzwäscheständer'
 ' verfügt über einen herausziehbaren Wäschesack und Stoffschublade, die es Ihnen ermöglichen, Ihre Wäsche'
 ' mühelos zu sortieren. Die Schublade des Wäschesortierers bietet sogar drei Fächer für Ihre Waschmittel'
 ' und Weichspüler. Der obere Ablagebereich schafft zusätzlichen Platz für alles, was Sie benötigen. Der'
 ' elegante Bambusrahmen verleiht jedem Raum einen Hauch von natürlichem Stil.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Zwillings-Taschen (eine davon enthält 3 Ebenen) und ein oberes Regal zur Aufbewahrung von'
 ' Vorräten</p></li>'
 '<li><p>✔ Ausgestattet mit zwei Griffen für einfachen Transport</p></li>'
 '<li><p>✔ Taschen sind abnehmbar und maschinenwaschbar</p></li>'
 '<li><p>✔ Das lamellierte Design des Wäschekorbs fördert die Luftzirkulation und reduziert Gerüche</p></li>'
 '<li><p>✔ Bambusrahmen des Wäsche-Sortiersystems gewährleistet Langlebigkeit und verleiht eine natürliche'
 ' Note</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß+Holz</p></li>'
 '<li><p>✔ Material: Bambus, Polyester</p></li>'
 '<li><p>✔ Gesamtabmessungen: 70B x 36T x 70H cm</p></li>'
 '<li><p>✔ Taschengröße: 27B x 32T x 44H cm</p></li>'
 '<li><p>✔ Regalgröße für Taschen: 29B x 31T x 16,5H cm</p></li>'
 '<li><p>✔ Oberflächengröße: 67B x 36T cm</p></li>'
 '<li><p>✔ Beinhöhe: 4 cm</p></li>'
 '<li><p>✔ Fassungsvermögen: 83L</p></li>'
 '<li><p>✔ Belastbarkeit: 13 kg (gesamt), 5 kg (Regal), 4 kg (pro Tasche)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Wäschekorb</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '70L x 36B x 70H cm</p></li>'
 + F + 'Färg:</span> Weiß</p></li>'
 + F + 'Material:</span> Bambus</p></li>'
 + F + 'Vikt:</span> 5 kg</p></li>'
 + F + 'Paketmått:</span> 76 × 42,5 × 10,3 cm</p></li></ul>'
)

if __name__ == "__main__":
    json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    for kort, html in K.items():
        print(f"{kort}\t{len(html)} tecken")
