#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska kalltexterna.

☠️ FILEN AR EN AVSKRIFT och far darfor inte litas pa. Kor
`kontrollera-kalla` (h*31 per produkt, server-side mot skarpa V3)
innan en enda grind korts — samma ordning som N26–N30. N27:s forsta
korning gav 7 av 8 och fallde ett akta transkriberingsfel med RATT
teckenantal men fel summa. Det ar SUMMAN som avgor, inte langden.
"""
import io, json, collections

K = collections.OrderedDict()

K["81bff775"] = (
 '<p>Träumen Sie von einem sichereren und zauberhaften Garten? Eine gewöhnliche Gartenbrücke kann für'
 ' ältere Menschen eine Herausforderung darstellen. Die Gartenbrücke verwandelt Ihren Garten mit ihrem'
 ' eleganten barocken Scroll-Design. Diese Bogenbrücke ist nicht nur dekorativ, sondern auch stabil und'
 ' wetterbeständig. Mit ihren 91 cm hohen Sicherheitsgeländern sorgt sie für ein sicheres Überqueren und'
 ' bietet sowohl beruhigende Sicherheit als auch dauerhafte Schönheit.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Eleganter Barockstil mit Rollwerk wird zum auffälligen Blickfang im Garten</p></li>'
 '<li><p>✔ Vollmetallkonstruktion trägt bis zu 100 kg für zuverlässige Nutzung</p></li>'
 '<li><p>✔ Eine pulverbeschichtete Oberfläche bietet wetterfeste Rost- und Farbbeständigkeit für'
 ' Langlebigkeit</p></li>'
 '<li><p>✔ Hohe Seitenwangen mit integrierten Handläufen der Zierbrücke bieten einen sicheren Halt für'
 ' mehr Sicherheit</p></li>'
 '<li><p>✔ Perfekt, um kleine Bäche zu überbrücken oder Gartenwege zu verschönern</p></li>'
 '<li><p>✔ Die kompakte Größe schafft der Teichbrücke eine charmante, malerische Szene in den meisten'
 ' Gartengestaltungen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 135,5L x 74B x 91H cm</p></li>'
 '<li><p>✔ Brückendeckgröße: 131L x 65,5B cm</p></li>'
 '<li><p>✔ Höhe des Bogens: 12 cm</p></li>'
 '<li><p>✔ Maximale Belastung: 100 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Gartenbrücke</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 135,5L x 74B x 91H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Schwarz</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 21,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 77 × 22 × 79 cm</p></li></ul>'
)

K["86c60239"] = (
 '<p>Dieser schicke Pavillon von verwandelt Ihren Außenbereich mit seinem eleganten und durchdachten'
 ' Design in einen praktischen und stylischen Treffpunkt. Das wasserabweisende Dach schützt Sie vor'
 ' UV-Strahlung und starker Sonneneinstrahlung und ist dabei dennoch lichtecht. Der pulverbeschichtete'
 ' Stahlrahmen und das Dach aus beschichtetem Polyester werden Ihnen über Jahre gute Dienste leisten.'
 ' Planen Sie jetzt schon Ihre nächste Gartenparty mit Ihrem neuen Pavillon und genießen Sie die warme'
 ' Jahreszeit in vollen Zügen!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Doppeldach-Design</p></li>'
 '<li><p>✔ Robuster Polyesterstoff mit PA-Beschichtung zum Schutz vor UV und starker'
 ' Sonneneinstrahlung</p></li>'
 '<li><p>✔ Praktisches Doppeldach mit Moskitonetz für bessere Luftzirkulation und Insektenschutz</p></li>'
 '<li><p>✔ Robuster pulverbeschichteter Metallrahmen</p></li>'
 '<li><p>✔Geregelter Wasserabfluss durch 8 Ösen</p></li>'
 '<li><p>✔ 8 Heringe zur Verankerung im Boden und 4 Abspannseile sorgen für zusätzliche'
 ' Stabilität</p></li>'
 '<li><p>Achtung: Lassen Sie den Pavillon nicht bei starkem Wind oder Unwetter aufgebaut, da es sonst zu'
 ' Schäden kommen kann.</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Material: Polyester, Metall</p></li>'
 '<li><p>✔ Farbe: Hellgrau</p></li>'
 '<li><p>✔ Gewicht: 12 kg</p></li>'
 '<li><p>✔ Gesamtmaße: 294L x 294B x 265H cm</p></li>'
 '<li><p>✔ Durchgangshöhe: 195 cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Pavillon</p></li>'
 '<li><p>✔ 8 x Hering, 4 x Abspannseil</p></li>'
 '<li><p>✔ 1 x Montageanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 294L x 294B x 265H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Hellgrau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Polyester/Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 13 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 198 × 27 × 13 cm</p></li></ul>'
)

K["a7c39a89"] = (
 '<p>Probleme mit einer beengten Wohnung ohne Essbereich? Das Bartisch-Set bietet Abhilfe. Es vereint'
 ' eine Essecke und eine Hausbar mit einem praktischen Weinregal und Glashaltern. Der industrielle Stil'
 ' des Bartisches bereichert Ihren Raum, während die Hocker platzsparend verstaut werden können. Ideal'
 ' als Frühstücksbereich oder zur Bewirtung von Freunden geeignet.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Das 3-teilige Bartisch Set umfasst einen rechteckigen Tisch und zwei runde Hocker</p></li>'
 '<li><p>✔ Integrierte Aufbewahrungsregale, Weinregale und Glashalter halten Ihre Bar-Utensilien'
 ' organisiert</p></li>'
 '<li><p>✔ Die Hocker können unter den Hochtisch gestellt werden, um Ihren begrenzten Wohnraum optimal'
 ' zu nutzen</p></li>'
 '<li><p>✔ Schicker Industriestil mit elegantem schwarzen Rahmen und Paneelen in Holzoptik</p></li>'
 '<li><p>✔ Getragen von robusten Stahlbeinen für Stärke und Stabilität</p></li>'
 '<li><p>✔ Fußstützen an den Barhockern zum Entspannen Ihrer Beine</p></li>'
 '<li><p>✔ Verstellbare Füße am Tisch gewährleisten Stabilität auf unebenen Böden</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Grau</p></li>'
 '<li><p>✔ Materialien: MDF, Stahl</p></li>'
 '<li><p>✔ Tischabmessungen: 121,5B x 40T x 122H cm</p></li>'
 '<li><p>✔ Hockerabmessungen: Ø30 x 60H cm</p></li>'
 '<li><p>✔ Tischplattengröße: 120B x 40T cm</p></li>'
 '<li><p>✔ Regalgröße: 40B x 35T cm (oben), 29B x 40T x 30H cm (unter dem Tisch), 29B x 40T x 13,5H cm'
 ' (unten)</p></li>'
 '<li><p>✔ Weinregalgröße: 29B x 40T x 13,5H cm</p></li>'
 '<li><p>✔ Maximale Belastung: 90 kg (Tisch), 120 kg (Hocker), 40 kg (Tischplatte), 10 kg'
 ' (Regal)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Bartisch</p></li>'
 '<li><p>✔ 2 x Barhocker</p></li>'
 '<li><p>✔ 1 x Gebrauchsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 121,5L x 40B x 122H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Grau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 28 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 135 × 48 × 17 cm</p></li></ul>'
)

K["cae81077"] = (
 '<p>Bringen Sie frischen Wind in Ihr Zuhause mit diesen 2er-Set Polsterstühlen in Lammwoll-Optik, die'
 ' modernen Komfort bieten. Schwarze Stahlbeine der Küchenstühle sorgen für eine moderne Note und die'
 ' ergonomische Rückenlehne passt sich perfekt an die Körperkonturen an und fördert eine gesunde'
 ' Sitzhaltung.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Set aus 2 Küchenstühlen mit weichem Stoffbezug in Lammwoll-Optik</p></li>'
 '<li><p>✔ Schwarze Stahllbeine für eine moderne Ästhetik</p></li>'
 '<li><p>✔ Esszimmerstuhl mit ergonomischer Rückenlehne für bequemen Halt</p></li>'
 '<li><p>✔ Rücken- und Sitzpolsterung mit einer Dicke von 5 cm, für optimalen Komfort</p></li>'
 '<li><p>✔ Sitzdichte von 24 kg/m³ für ausgewogenen Support</p></li>'
 '<li><p>✔ Elegantes und zeitgemäßes Design, passend zu verschiedenen Dekorationsstilen</p></li>'
 '<li><p>✔ Langlebige Materialien für eine lange Lebensdauer der Essstühle</p></li>'
 '<li><p>✔ Perfekt, um Ihrem Wohnbereich Stil und Komfort hinzuzufügen</p></li>'
 '<li><p>✔ Beine mit rutschfesten Pads, um den Boden zu schonen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Cremeweiß+Schwarz</p></li>'
 '<li><p>✔ Material: Polyester, Stahl, Schaumstoff, Mehrschichtenplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 55L x 62B x 80H cm</p></li>'
 '<li><p>✔ Sitzgröße: 48L x 47T x 46H cm</p></li>'
 '<li><p>✔ Rückenlehnenmaße: 41L x 39H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 2 x Esszimmerstühle</p></li>'
 '<li><p>✔ 1 x Montageanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 55L x 62B x 80H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Beige</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Polyester</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 15 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 67 × 57 × 49 cm</p></li></ul>'
)

K["07d1208e"] = (
 '<p>Absolvieren Sie Ihr Cardio-Training ganz unabhängig von Wind und Wetter! Mit diesem Fahrradtrainer'
 ' trainieren Sie zuverlässig und effektiv auf Ihre persönliche Topform zu. Der Trittwiderstand kann'
 ' ganz nach Ihrem persönlichen Trainingsniveau eingestellt werden. Lenker und Sattel lassen sich'
 ' ebenfalls anpassen, sodass Sie stets komfortabel trainieren. Lesen Sie Ihre Trainingsdaten wie Zeit,'
 ' Geschwindigkeit, Distanz, Herzfrequenz oder Kalorienverbrauch bequem von der digitalen Anzeige'
 ' ab.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Hochwertiger Heimtrainer für den privaten Gebrauch</p></li>'
 '<li><p>✔ Starke Stahlkonstruktion mit rutschfesten Füßen für hohe Stabilität</p></li>'
 '<li><p>✔ LCD-Display zeigt Trainingsdaten wie Zeit, Geschwindigkeit, Distanz und'
 ' Kalorienverbrauch</p></li>'
 '<li><p>✔ Tretwiderstand durch Filzwiderstand stufenlos einstellbar</p></li>'
 '<li><p>✔ Sitz horizontal verstellbar und höhenverstellbar</p></li>'
 '<li><p>✔ Lenker und Griff sind ebenfalls höhenverstellbar</p></li>'
 '<li><p>✔ Mit Halterung für Ihr Smartphone</p></li>'
 '<li><p>✔ Leicht zu bewegen dank der 2 Rollen</p></li>'
 '<li><p>✔ Einfache Montage</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Material: Stahl, ABS</p></li>'
 '<li><p>✔ Gesamtmaß: L85 x B46 x H114 cm</p></li>'
 '<li><p>✔ Sitzhöhe: 78-93 cm</p></li>'
 '<li><p>✔ Höhe des Handgriffs: 104-114 cm</p></li>'
 '<li><p>✔ Sitzgröße: L24 x B22 cm</p></li>'
 '<li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Max. Belastbarkeit: 100 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1x Fahrradtrainer</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> L85 x B46 x H114 cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß, Beige, Braun</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Legierter Stahl</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 21,3 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 87,5 × 21,3 × 73,8 cm</p></li></ul>'
)

K["cec4d9a9"] = (
 '<p>Viele Tischfußballspiele sind instabil und wenig stilvoll. Der Tischkicker punktet mit niedlichem'
 ' Bärendesign und verstärkten, schrägen Beinen und bleibt auch bei intensivem Spiel sicher stehen.'
 ' 22 Spieler, ein großes Spielfeld und rutschfeste Griffe machen den Fußballtisch zum Mittelpunkt'
 ' spaßiger, stilvoller Familien-Wettkämpfe im Spielzimmer.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 22 farbcodierte Spieler für authentisches Spiel auf dem Tischkicker, in einer'
 ' 3-4-3-Formation und jeweils ein Torwart pro Team</p></li>'
 '<li><p>✔ 360°-Stangen mit strukturierten Griffen und Puffern für ein präzises, leises Spiel am'
 ' Kickertisch</p></li>'
 '<li><p>✔ Zwei manuelle Zählwerke (0–9) für schnelle Ergebniserfassung beim Tischfussball</p></li>'
 '<li><p>✔ Tor mit Öffnungen für einfachen Zugriff auf die Bälle (zwei Mini-Bälle inklusive)</p></li>'
 '<li><p>✔ Robuste MDF-Struktur mit verstärkten, ausgestellten Beinen für intensive Partien</p></li>'
 '<li><p>✔ Lebendiger Stil mit grünem Spielfeld und niedlichem Bärenmuster für eine verspielte'
 ' Optik</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Naturholz+Grün+Hellgrau</p></li>'
 '<li><p>✔ Material: MDF, Kunststoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 121L x 87B x 77H cm</p></li>'
 '<li><p>✔ Spielfeldgröße: 105L x 58B cm</p></li>'
 '<li><p>✔ Balldurchmesser: Ø32 mm</p></li>'
 '<li><p>✔ Zählerlänge: 16,3 cm</p></li>'
 '<li><p>✔ Steuerstangengröße: Ø1,2 x 77,5L cm, Ø1,2 x 80L cm</p></li>'
 '<li><p>✔ Griffgröße: Ø3 x 9,5 cm</p></li>'
 '<li><p>✔ Empfohlenes Alter: 7+</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Tischfußball</p></li>'
 '<li><p>✔ 2 x Mini-Fußball</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 121L x 87B x 77H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Naturholz</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 18 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 128 × 75 × 10 cm</p></li></ul>'
)

K["fda8a9de"] = (
 '<p>Wenn das Gras am Wochenende sprießt, werden ungleichmäßige Schnitte und Leistungsabfälle schnell'
 ' zur Herausforderung. Dicke, feuchte Stellen überfordern Standardgeräte, und unsicherer Akkustand'
 ' kann Arbeit unterbrechen. Der Rasenmäher bietet 40 cm Schnittbreite, 25–75 mm Höheneinstellung per'
 ' Hebel und einen 36V 800W bürstenlosen Motor. Die integrierte Akkuanzeige des elektrischen'
 ' Rasenmähers erleichtert entspanntes und planvolles Mähen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 40 cm Schnittbreite deckt mehr Fläche ab und ermöglicht ein schnelleres Rasenmähen</p></li>'
 '<li><p>✔ Sieben Höheneinstellungen von 25–75 mm sorgen für saubere, gleichmäßige Schnitte, ideal für'
 ' jeden Rasenmäher</p></li>'
 '<li><p>✔ Der 36 V 800 W bürstenlose Motor hält die Leistung stabil und verringert den Verschleiß bei'
 ' diesem Elektro Rasenmäher</p></li>'
 '<li><p>✔ Eingebauter Batterieanzeiger zeigt die verbleibende Ladung an und verhindert'
 ' Arbeitsunterbrechungen</p></li>'
 '<li><p>✔ Doppelter Sicherheitsschalter plus Überlastschutz reduziert Unfälle und verhindert'
 ' Schäden</p></li>'
 '<li><p>✔ 45 L Grasfangbox sammelt Schnittgut effizient und verringert die Häufigkeit des'
 ' Entleerens</p></li>'
 '<li><p>✔ Verstellbarer Griff und klappbares Design verbessern den Komfort und sparen'
 ' Stauraum.</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Rot+Schwarz</p></li>'
 '<li><p>✔ Material: Kunststoff, Metall, Kupfer</p></li>'
 '<li><p>✔ Gesamtabmessungen: 131L x 46B x 109H cm</p></li>'
 '<li><p>✔ Fassungsvermögen der Grasbox: 45L</p></li>'
 '<li><p>✔ Lenkerlänge: 38,5 cm</p></li>'
 '<li><p>✔ Schnittbreite: 40 cm</p></li>'
 '<li><p>✔ Schnitthöhe: 2,5-7,5 cm</p></li>'
 '<li><p>✔ Motorleistung: 800W</p></li>'
 '<li><p>✔ Spannung: 36V</p></li>'
 '<li><p>✔ Stromkabel: 1,1 m</p></li>'
 '<li><p>✔ Hinweis: 1, Dieses Produkt enthält keinen Akku oder Ladegerät und ist mit'
 ' Makita-kompatiblen Akkus kompatibel.2, Das Mähen von übermäßig hohem Gras oder dichtem Unkraut kann'
 ' die Leistung beeinträchtigen und den Überhitzungsschutz des Motors auslösen. Bei starker Vegetation'
 ' verwenden Sie vor dem Mähen einen Freischneider oder Rasentrimmer</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Rasenmäher</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 131L x 46B x 109H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Rot</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Kunststoff/Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 16,7 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 76 × 46,5 × 45,5 cm</p></li></ul>'
)

K["180f81c1"] = (
 '<p>Entdecken Sie den Rattan-Hollywoodschaukel: 110 cm pure Entspannung, perfekt um Zeit mit Freunden'
 ' zu verbringen. Die hochdichten Schaumstoffkissen mit waschbaren Bezügen des Rattan-Hollywoodschaukels'
 ' garantieren Komfort und einfache Pflege. Der robuste, pulverbeschichtete Stahlrahmen und das PE-Rattan'
 ' des Rattan-Hollywoodschaukels widerstehen Verformungen und sorgen für langanhaltende Festigkeit Ihres'
 ' gemütlichen Gartenrefugiums.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 110 cm breites Sitzkissen des Rattan-Hollywoodschaukels bietet bequem Platz für zwei'
 ' Personen</p></li>'
 '<li><p>✔ Hochdichter Schaumstoffpolster des Rattan-Hollywoodschaukels sorgt für weiches, stützendes'
 ' Sitzen</p></li>'
 '<li><p>✔ Kissenbezüge mit Reißverschlüssen, abnehmbar und waschbar für einfache Pflege</p></li>'
 '<li><p>✔ Pulverbeschichteter Stahlrahmen des Rattan-Hollywoodschaukels gewährleistet außergewöhnliche'
 ' Haltbarkeit</p></li>'
 '<li><p>✔ PE-Rattan-Ummantelung widersteht Verformungen und erhöht die Festigkeit</p></li>'
 '<li><p>✔ Geeignet für gemütliche Ecken in Gärten, auf Terrassen oder Balkonen</p></li>'
 '<li><p>✔ Einfache Montage</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Naturholz+Beige</p></li>'
 '<li><p>✔ Material: Stahl, PE-Rattan, Polyester</p></li>'
 '<li><p>✔ Gesamtabmessungen: 115L x 66B x 44H cm</p></li>'
 '<li><p>✔ Sitzgröße: 110B x 54T cm</p></li>'
 '<li><p>✔ Rückenlehnen-Größe: 109B x 38H cm</p></li>'
 '<li><p>✔ Sitzkissengröße: 111B x 54H cm</p></li>'
 '<li><p>✔ Rückenkissengröße: 58B x 42H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 240 kg</p></li>'
 '<li><p>✔ Hinweis: Der Ständer ist nicht im Lieferumfang enthalten</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Rattan-Hängesessel</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 115 x 66 x 44 cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Beige</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> PE-Rattan</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 16,4 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 117 × 60 × 28 cm</p></li></ul>'
)

json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)


def summa(s):
    h = 0
    for c in s:
        h = (h * 31 + (ord(c) & 0xFFFF)) % 1000000007
    return h


for k, v in K.items():
    print("%s\t%d\t%d" % (k, summa(v), len(v)))
