#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska källtexterna (hämtade server-side
via ExecuteWixAPI mot skarpa V3, ?fields=PLAIN_DESCRIPTION).

☠️ FILEN ÄR EN AVSKRIFT och får därför inte litas på. Kör kontrollen mot
skarpa V3 (samma anrop som ingen skrivning) innan en enda grind körs — samma
ordning som N26–N41. Det är SUMMAN som avgör, inte längden.

☠️ EN KÄLLTEXT BÄR LEVERANTÖRENS ARTIKELNUMMER i sin `Technische Daten`:
`988ac121` ("Artikelnummer: ‹REDIGERAT›"). Repot är publikt, så numret är
ersatt med ‹REDIGERAT› här. Kontrollsumman mot Wix räknas därför på texten
EFTER samma ersättning, med exakt EN träff på den och noll på de andra nio —
samma form som N34/N35/N41. Annars hade den produkt där avskriften medvetet
avviker sett ut som ett transkriberingsfel.
"""
import io, json, collections

K = collections.OrderedDict()

SPEC = '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> '
F = '<li><p><span style="font-weight: 700">'

K["2cfd222e"] = (
 '<p>Lieben Sie Pflanzen, möchten aber eine pflegeleichte Lösung? Unsere Kunstpflanze ist die perfekte Wahl für Ihre'
 ' Bedürfnisse und jeden Raum. Reinigen Sie sie einfach mit einem feuchten Tuch wie jedes andere Möbelstück – kein'
 ' Gießen, Beschneiden oder der richtige Platz für Sonnenlicht erforderlich. Diese grüne Pflanze wertet Ihre Innen-'
 ' oder Außendekoration sofort auf!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dekorative Kunstpflanze mit realistischem Aussehen für den Innen- (Zuhause, Büro) oder Außenbereich</p></li>'
 '<li><p>✔ Diese grüne Pflanze hat 33 Blätter für ein authentisches, natürliches Erscheinungsbild</p></li>'
 '<li><p>✔ Im Gegensatz zu echten Pflanzen benötigt diese Kunstpflanze kein Gießen oder Beschneiden, verwelkt nie und'
 ' kann in Bereichen ohne Licht aufgestellt werden</p></li>'
 '<li><p>✔ Robuster Topf mit verstärktem Zementsockel und synthetischem Moos obenauf</p></li>'
 '<li><p>✔ Pflegeleichte Dekopflanze mit minimalem Wartungsaufwand</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Grün und Schwarz</p></li>'
 '<li><p>✔ Material: PEVA, PE und Zement</p></li>'
 '<li><p>✔ Gesamthöhe: 95 cm</p></li>'
 '<li><p>✔ Anzahl der Blätter: 33</p></li>'
 '<li><p>✔ Topfabmessungen: Ø15 x 13 cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Kunstpflanze;</p></li></ul>'
 + SPEC + 'Höhe 95 cm</p></li>'
 + F + 'Färg:</span> Grün</p></li>'
 + F + 'Material:</span> Polyethylen/Ethylen-Vinylacetat</p></li>'
 + F + 'Vikt:</span> 3 kg</p></li>'
 + F + 'Paketmått:</span> 100 × 19 × 19 cm</p></li></ul>'
)

K["3e2c7389"] = (
 '<p>Schaffen Sie eine einladende Atmosphäre mit der Schuhbank aus natürlichem Bambus. Die zwei großzügigen Ablagen'
 ' der Sitzbank bieten Platz für bis zu sechs Paar Schuhe, während die stabile Sitzfläche mit einer Tragkraft von'
 ' 130 kg Komfort und Sicherheit beim Schuheanziehen gewährleistet. Dank des modernen Designs fügt sich die Flurbank'
 ' harmonisch in jeden Raum ein und sorgt für ein entspanntes, ordentliches Zuhause.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Hergestellt aus hochwertigem Bambus, bietet die Schuhbank eine natürliche Ästhetik</p></li>'
 '<li><p>✔ Vielseitiges Design kombiniert Schuhregal und Sitzbank für maximalen Platzgewinn</p></li>'
 '<li><p>✔ Zwei Ablagen bieten Platz für insgesamt 6 Paar Schuhe, ideal für verschiedene Schuhgrößen</p></li>'
 '<li><p>✔ Robuste Konstruktion mit einer Tragfähigkeit von bis zu 136kg für sicheren Gebrauch</p></li>'
 '<li><p>✔ Ergonomisch gestalteter Sitz bietet Komfort beim Schuhewechseln</p></li>'
 '<li><p>✔ Schlichtes natures Design der Flurbank passt zu verschiedenen Einrichtungsstilen und verbessert die'
 ' Raumästhetik</p></li>'
 '<li><p>✔ 5cm Bodenfreiheit der Garderobenbank erleichtert die Reinigung und hält den Boden sauber</p></li>'
 '<li><p>✔ Einfacher Aufbau dank zerlegbarer Struktur, ideal für kleine Wohnungen</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Naturholz</p></li>'
 '<li><p>✔ Material: Bambus</p></li>'
 '<li><p>✔ Gesamtabmessungen: 70L x 28B x 45H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 130 kg (oben), 3 kg (jede Regalebene)</p></li>'
 '<li><p>✔ Geeignet für Schuhgrößen bis maximal 46 (EU)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Schuhbank</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '70L x 28B x 45H cm</p></li>'
 + F + 'Färg:</span> Naturholz</p></li>'
 + F + 'Material:</span> Bambus</p></li>'
 + F + 'Vikt:</span> 4,5 kg</p></li>'
 + F + 'Paketmått:</span> 78 × 33,5 × 7,8 cm</p></li></ul>'
)

K["5c5aedca"] = (
 '<p>Weiß ist die edle Farbe des Winters. Auch wenn es in vielen Teilen Deutschlands nicht immer weiße Weihnacht gibt,'
 ' lässt sich hier doch Abhilfe schaffen. Unser künstlicher Weihnachtsbaum in schneeweiß ist etwas ganz Besonderes'
 ' für Sie. Er zaubert Ihr Zuhause in ein kleines Winterwunderland. Und das ohne zu nadeln, oder seine Zweigpracht'
 ' über die Zeit zu senken. Neben seinem extravaganten Auftreten, bringt unser Christbaum alle Vorteile eines'
 ' künstlichen Baumes mit sich. Mehrmals wiederverwendbar, kein Nadeln, keine lästige Entsorgung und er lässt sich'
 ' komfortabel auch neben der Heizung aufstellen. Ganz ohne Brandgefahr oder auszutrocknen. Der Baum wird Ihnen bequem'
 ' nach Hause geliefert. Der Aufbau ist kinderleicht und beiliegend ist eine dezente Auswahl schöner'
 ' Weihnachtsbaumdekoration. Lassen Sie es edel weihnachten bei sich Zuhause!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Kunst-Weihnachtsbaum in Weiß</p></li>'
 '<li><p>✔ Inkl. Metallständer</p></li>'
 '<li><p>✔ Nadeln aus Kunststoff sind schwer entflammbar</p></li>'
 '<li><p>✔ Insgesamt Zweigspitzen</p></li>'
 '<li><p>✔ Inkl. Deko: mehrfarbige Kugeln, Trommeln, Geschenkkartons, 1 goldene Glocke, Kiefernzapfen</p></li>'
 '<li><p>✔ Wiederverwendbar</p></li>'
 '<li><p>✔ Nicht für den Außenbereich geeignet</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Material: Metall, PVC</p></li>'
 '<li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Gesamtmaße: ø85 x H150 cm</p></li>'
 '<li><p>✔ Anzahl der Spitzen:</p></li>'
 '<li><p>✔ Nettogewicht: 3,2 kg</p></li>'
 '<li><p>✔ Marke: bei </p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Weihnachtsbaum</p></li>'
 '<li><p>✔ 1 x Metallständer</p></li>'
 '<li><p>✔ Deko: 18 x mehrfarbige Kugeln, 6 x goldene Glocken, 6 x mehrfarbige Trommeln, 6 x mehrfarbige'
 ' Geschenkboxen, 12 x goldene Tannenzapfen</p></li></ul>'
 + SPEC + '150 cm</p></li>'
 + F + 'Färg:</span> Weiß</p></li>'
 + F + 'Material:</span> Metall/Polyvinylchlorid</p></li>'
 + F + 'Vikt:</span> 3,9 kg</p></li>'
 + F + 'Paketmått:</span> 73 × 16 × 18 cm</p></li></ul>'
)

K["7f21945e"] = (
 '<p>Die 3 unterschiedlich großen Körbe von bieten vielseitige Aufbewahrungsmöglichkeiten und ausreichend Platz zur'
 ' Organisation. Handgefertigte Flechtkunst verleiht dem Raumdekor natürlichen Stil. Hochwertiger Kunststoff sorgt für'
 ' Stabilität. Mit Deckeln und Schnallen bleiben Gegenstände sicher. Das leichte Design erleichtert den Transport.'
 ' Diese Körbe bringen Stil und Ordnung in jedes Zimmer.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 3 unterschiedlich große Körbe bieten vielseitigen Stauraum in Küche, Waschküche und Schlafzimmer</p></li>'
 '<li><p>✔ Die Schönheit der Natur spiegelt sich im handgeflochtenen Rattan wider und bringt Eleganz und Wärme in Ihr'
 ' Zuhause</p></li>'
 '<li><p>✔ Hochwertiger PP-Kunststoff ist verschleißfest und der Metallrahmen sorgt für hohe Festigkeit</p></li>'
 '<li><p>✔ Ein Deckel hält Ihre Unordnung verborgen, und Schnallen schützen Ihre Sachen</p></li>'
 '<li><p>✔ Organisation von Spielzeug, Büchern, Kunsthandwerk, Kleidung, Babyartikeln, Socken, DVDs und mehr</p></li>'
 '<li><p>✔ Lässt Luft durch und verhindert so die Bildung von Gerüchen</p></li>'
 '<li><p>✔ Keine Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Grau</p></li>'
 '<li><p>✔ Material: PP, Metall</p></li>'
 '<li><p>✔ Gesamtmaße: 35,5L x 28,5B x 18H cm (groß), 33L x 24B x 15H cm (mittel), 28L x 20B x 12,5H cm'
 ' (klein)</p></li>'
 '<li><p>✔ Fassungsvermögen: 18L, 12L, 7L</p></li>'
 '<li><p>✔ Maximale Belastbarkeit: 5kg (jeder)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 3 x Aufbewahrungskorb</p></li></ul>'
 + SPEC + '35,5L x 28,5B x 18H cm</p></li>'
 + F + 'Färg:</span> Grau</p></li>'
 + F + 'Material:</span> Kunststoff</p></li>'
 + F + 'Vikt:</span> 2 kg</p></li>'
 + F + 'Paketmått:</span> 37 × 29,5 × 20 cm</p></li></ul>'
)

K["985ff6d3"] = (
 '<p>Fühlt sich Ihre Morgenroutine wie ein Balanceakt an? Eine Person möchte leicht goldenen Toast, eine andere mag'
 ' ihn dunkel, und jemand hat vergessen, das Brot aufzutauen. Der 2-Scheiben-Toaster vereinfacht alles mit sieben'
 ' Bräunungsstufen, die jedem gefallen. Seine Auftaufunktion rettet den Tag, während ein Wärmerost sanft Croissants'
 ' erhitzt. Dieser Toaster bringt Ruhe und Vielfalt zurück auf Ihren Frühstückstisch und sorgt für einen'
 ' reibungsloseren Start in den Tag für die ganze Familie.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Der Toaster verfügt über sieben Bräunungsstufen für perfekt individuell angepassten Toast jedes Mal</p></li>'
 '<li><p>✔ Enthält Auftau-, Aufwärm- und Abbruchfunktionen für eine vielseitige Frühstückszubereitung mit diesem'
 ' 2-Scheiben-Toaster</p></li>'
 '<li><p>✔ Mit praktischem Warmhalterost für das sanfte Erwärmen von Croissants und Muffins</p></li>'
 '<li><p>✔ Zwei 13,5 cm lange Schlitze mit automatischer Zentrierung sorgen bei diesem Toaster für gleichmäßig'
 ' getoastetes Brot</p></li>'
 '<li><p>✔ Herausnehmbare Krümelschublade ermöglicht eine schnelle Reinigung und hält Ihre Küche ordentlich</p></li>'
 '<li><p>✔ Automatische Abschaltung und Kurzschlussschutz bieten erhöhte Sicherheit während des Gebrauchs</p></li>'
 '<li><p>✔ Rutschfeste Füße halten den Toaster stabil und sicher.</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz+Silber</p></li>'
 '<li><p>✔ Material: Kunststoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 26,4L x 15,6B x 18,9H cm</p></li>'
 '<li><p>✔ Größe jedes Fachs: 13,5L x 3,5B x 12,5H cm</p></li>'
 '<li><p>✔ Eingang: 220-240V 50/60Hz</p></li>'
 '<li><p>✔ Ausgang: 780-930W</p></li>'
 '<li><p>✔ Kabellänge: 0,7 m</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Toaster</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '26,4cm x 15,6cm x 18,9cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Kunststoff/Polypropylen (PP)</p></li>'
 + F + 'Vikt:</span> 1,65 kg</p></li>'
 + F + 'Paketmått:</span> 31 × 21 × 21 cm</p></li></ul>'
)

K["988ac121"] = (
 '<p>Ein gemütliches Kaminfeuer wirkt entspannter, wenn keine Funken fliegen und Kinder oder Haustiere Abstand'
 ' halten. Das Kaminschutzgitter bildet eine hitzebeständige Schutzbarriere. Schwarze Paneele im geometrischen Design'
 ' sorgen für eine stilvolle, aufgeräumte Optik. Das Ofenschutzgitter lässt sich flexibel anpassen und platzsparend'
 ' zusammenklappen – für mehr Ruhe, Wärme und Ordnung am Kamin.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Das Kaminschutzgitter hilft als Funkenschutzgitter, Funken abzuhalten und hält Kinder und Haustiere weiter'
 ' vom Kaminbereich fern</p></li>'
 '<li><p>✔ Schwarzes Metall mit Pulverbeschichtung eignet sich hervorragend für den täglichen Gebrauch als'
 ' Ofenschutzgitter</p></li>'
 '<li><p>✔ Geometrische Details und klare Linien passen gut zu Gaskaminen und Kaminbesteck, sodass sich das'
 ' Kamingitter harmonisch einfügt</p></li>'
 '<li><p>✔ Das dreiteilige Design lässt sich einfach anpassen, sodass das Kaminschutzgitter zu unterschiedlichen'
 ' Raumaufteilungen passt</p></li>'
 '<li><p>✔ Zusammenklappbar auf 58 x 2 x 51 cm (B x T x H) für eine kompakte saisonale Aufbewahrung</p></li>'
 '<li><p>✔ Mit 100 x 1 x 51 cm (B x T x H) deckt es den Kaminbereich ordentlich ab und eignet sich gut als'
 ' Ofengitter</p></li>'
 '<li><p>✔ Sofort einsatzbereit, sodass Aufstellen und Umpositionieren schnell und einfach bleiben</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 100B x 1T x 51H cm</p></li>'
 '<li><p>✔ Maße zusammengeklappt: 58B x 2T x 51H cm</p></li>'
 '<li><p>✔ Abmessungen der Seitenwand: 20B x 1T x 50H cm</p></li>'
 '<li><p>✔ Artikelnummer: ‹REDIGERAT›</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Funkenschutzgitter</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '100 x 1 x 51 cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 3 kg</p></li>'
 + F + 'Paketmått:</span> 65 × 6 × 57,5 cm</p></li></ul>'
)

K["b138effc"] = (
 '<p>Der -Frisiertischarm ist eine praktische Wahl für professionelle oder private Hundefriseure. Mit der'
 ' höhenverstellbaren Pflegestange eignet er sich für mittelgroße Hunde und erleichtert das Baden, Trimmen, Trocknen'
 ' und Pflegen. Die Klemme sorgt für eine sichere Befestigung am Tisch, während eine Pflegeschlaufe und zwei'
 ' zusätzliche Befestigungsseile mehr Halt während der Pflege bieten.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Der Edelstahlrahmen ist stabil und langlebig</p></li>'
 '<li><p>✔ Zusammenklappbar für eine einfache Aufbewahrung</p></li>'
 '<li><p>✔ Die höhenverstellbare Stange ist mit einer Pflegeschlaufe und zwei zusätzlichen Befestigungsseilen'
 ' ausgestattet und eignet sich für mittelgroße Hunde</p></li>'
 '<li><p>✔ Das Gestell kann sicher an den meisten Frisiertischen mit einer maximalen Dicke von 2,7 cm befestigt'
 ' werden</p></li>'
 '<li><p>✔ Geeignet für mittelgroße Hunde mit einem Gewicht von bis zu 20 kg und einer Schulterhöhe von weniger als'
 ' 50 cm</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Silber</p></li>'
 '<li><p>✔ Material: Aluminium, Edelstahl</p></li>'
 '<li><p>✔ Gesamtabmessungen: 36L x 8B x 74H cm</p></li>'
 '<li><p>✔ Maße der Arme: 74 cm (lang), 35,5 cm (kurz)</p></li>'
 '<li><p>✔ Höhe des Pflegearms: max. 65 cm (vom Tisch aus)</p></li>'
 '<li><p>✔ Abmessungen zusammengeklappt: 13L x 8B x 74H cm</p></li>'
 '<li><p>✔ Abmessungen des Geschirrs: 36 cm (grün), 45 cm (rot)</p></li>'
 '<li><p>✔ Abmessungen der Pflegeschlaufe: 40 cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Toilettenarm;</p></li></ul>'
 + SPEC + '36L x 8B x 74H cm</p></li>'
 + F + 'Färg:</span> Silber</p></li>'
 + F + 'Material:</span> Edelstahl</p></li>'
 + F + 'Vikt:</span> 1,5 kg</p></li>'
 + F + 'Paketmått:</span> 76 × 17 × 7,5 cm</p></li></ul>'
)

K["cfb722e4"] = (
 '<p>Entdecken Sie den Küchenwagen mit Rollen, Ihren cleveren Helfer zur Platzoptimierung! Dieser schlanke, nur 13 cm'
 ' breite Rollwagen gleitet nahtlos in schmale Zwischenräume und nutzt mit seinen 5 Etagen, vier Gitterkörben und'
 ' einer eleganten Holzoptik-Arbeitsplatte jeden Zentimeter optimal. Auf 360° drehbaren Rollen lässt der Servierwagen'
 ' sich leicht manövrieren, ideal um Küchen, Bäder oder Wäschereien spielend leicht aufzuräumen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Schmaler 13 cm Küchenwagen mit Rollen passt leicht in enge Lücken und nutzt Ihren Raum optimal</p></li>'
 '<li><p>✔ Fünfstufige Lagerung des Servierwagens maximiert den vertikalen Raum für effiziente Organisation</p></li>'
 '<li><p>✔ Maschenkörbe des Rollwagens sorgen für gute Luftzirkulation und halten die Gegenstände frisch</p></li>'
 '<li><p>✔ Die Arbeitsplatte in Holzoptik des Küchenwagens dient als zusätzliche Arbeitsfläche in der Küche</p></li>'
 '<li><p>✔ Leichtgängige Drehrollen und ein seitlicher Griff des Küchenwagens mit Arbeitsplatte erleichtern das'
 ' Bewegen überallhin</p></li>'
 '<li><p>✔ Bremsen an zwei Rädern halten den Wagen sicher an Ort und Stelle</p></li>'
 '<li><p>✔ Solider Metallrahmen bietet starke Unterstützung, mit einer wasserresistenten Melamin-Oberfläche, die'
 ' leicht zu reinigen ist</p></li>'
 '<li><p>✔ Ideal für Küchen, Badezimmer, Waschräume und andere Bereiche</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz+Rustikales Braun</p></li>'
 '<li><p>✔ Material: Metall, Spanplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 47L x 13B x 96,5H cm</p></li>'
 '<li><p>✔ Oberflächengröße: 41L x 13B cm</p></li>'
 '<li><p>✔ Korbgröße: 38L x 12B x 7H cm</p></li>'
 '<li><p>✔ Höhe pro Ebene: 23 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 11 kg (gesamt), 3 kg (oben), 2 kg (Korb)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Aufbewahrungswagen</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '47L x 13B x 96,5H cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall/Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 3,8 kg</p></li>'
 + F + 'Paketmått:</span> 53,5 × 20,5 × 18,5 cm</p></li></ul>'
)

K["dcf149d1"] = (
 '<p>Ermöglichen Sie Ihren Kindern mit dem Kinder Tritthocker mehr Selbstständigkeit! Der Kinderhocker lässt sich von'
 ' drei auf zwei Stufen verstellen und passt sich an Ihr wachsendes Kind an. Seine trapezförmige Bauweise und die'
 ' rutschfeste Oberfläche sorgen für Sicherheit beim Klettern. Ob als Hilfe in der Küche, im Bad oder neben dem Bett –'
 ' dieser Klohocker stärkt das Selbstvertrauen bei jedem Schritt.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Die verstellbare Höhe des Lernturms lässt sich von 3 auf 2 Stufen umstellen, für vielseitige'
 ' Nutzung</p></li>'
 '<li><p>✔ Trapezförmige Struktur des Badhockers gewährleistet Stabilität während der Benutzung</p></li>'
 '<li><p>✔ Rutschfeste Oberfläche und Fußpolster des Klohockers erhöhen die Sicherheit</p></li>'
 '<li><p>✔ Hergestellt aus robustem, leicht zu reinigendem Kunststoff-Material</p></li>'
 '<li><p>✔ Vielseitiges Design, geeignet als Küchen-, Badezimmer- oder Betthocker</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Grau+Cremeweiß</p></li>'
 '<li><p>✔ Material: Kunststoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 43L x 42B x 65,5H cm</p></li>'
 '<li><p>✔ Stufengröße: 36B x 17,5T cm</p></li>'
 '<li><p>✔ Stufenhöhe: 14,5/25/35,8H cm (zum Boden)</p></li>'
 '<li><p>✔ Maximale Belastung: 30 kg</p></li>'
 '<li><p>✔ Empfohlenes Alter: 2-5 Jahre</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Tritthocker für Kinder</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '43L x 42B x 65,5H cm</p></li>'
 + F + 'Färg:</span> Grau</p></li>'
 + F + 'Material:</span> Kunststoff</p></li>'
 + F + 'Vikt:</span> 3,6 kg</p></li>'
 + F + 'Paketmått:</span> 70 × 11 × 44 cm</p></li></ul>'
)

K["fd940665"] = (
 '<p>Der Konsolentisch vereint modernes Design mit Funktionalität. In Fluren oder Wohnzimmern schafft er mit seiner'
 ' Naturholzoptik und dem schwarzen Stahlgestell eine inspirierende Atmosphäre. Der geräumige Schrank des Flurtisches'
 ' bietet Platz für Schlüssel und Dokumente, während das platzsparende Design Ordnung in jedem Raum ermöglicht.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Der Konsolentisch mit Holzoptik und schwarzem Stahlrahmen verleiht Ihrem Raum einen Industrie-Chic</p></li>'
 '<li><p>✔ Der Schrank des Flurtisches bietet praktischen Stauraum für persönliche Gegenstände</p></li>'
 '<li><p>✔ Auf der Tischplatte können Sie Vasen, Fotos und andere Dekorationen stilvoll präsentieren</p></li>'
 '<li><p>✔ Aluminiumlegierungsgriff des Konsolentisches ermöglicht einfaches Öffnen und Schließen des'
 ' Schranks</p></li>'
 '<li><p>✔ Bodenschoner schützen Ihren Boden vor Kratzern und sorgen für Langlebigkeit</p></li>'
 '<li><p>✔ Melaminbeschichtete Oberfläche des Flurtisches ist glatt und leicht zu reinigen, ideal für den täglichen'
 ' Gebrauch</p></li>'
 '<li><p>✔ Erhöhter Boden erleichtert die Reinigung und sorgt für ein sauberes Zuhause</p></li>'
 '<li><p>✔ Einfache Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Natur+Schwarz</p></li>'
 '<li><p>✔ Material: Spanplatte, Stahl</p></li>'
 '<li><p>✔ Gesamtmaße: 40L x 30B x 76H cm</p></li>'
 '<li><p>✔ Innenmaße des Schranks: 37L x 28,5B x 27H cm</p></li>'
 '<li><p>✔ Höhe der Beine: 46 cm</p></li>'
 '<li><p>✔ Gewichtskapazität: 25 kg (gesamt), 10 kg (Schrank)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Konsolentisch</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '40L x 30B x 76H cm</p></li>'
 + F + 'Färg:</span> Naturholz</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 9,3 kg</p></li>'
 + F + 'Paketmått:</span> 56 × 37 × 17 cm</p></li></ul>'
)


def summa(s):
    h = 0
    for c in s:
        h = (h * 31 + (ord(c) & 0xFFFF)) % 1000000007
    return h


if __name__ == "__main__":
    with io.open("kallor.json", "w", encoding="utf-8") as f:
        json.dump(K, f, ensure_ascii=False, indent=1)
    for k, v in K.items():
        print(k, len(v), summa(v))
