#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska kalltexterna.

☠️ FILEN AR EN AVSKRIFT och far darfor inte litas pa. Kor
`kontrollera-kalla` (h*31 per produkt, server-side mot skarpa V3)
innan en enda grind korts — samma ordning som N26–N29. N27:s forsta
korning gav 7 av 8 och fallde ett akta transkriberingsfel med RATT
teckenantal men fel summa. Det ar SUMMAN som avgor, inte langden.
"""
import io, json, collections

K = collections.OrderedDict()

K["82d04879"] = (
 '<p>Entdecken Sie das Hühnergehege! Aus robustem Stahl und beschichtetem Draht gefertigt, bietet das'
 ' Freilaufgehege Platz zum Scharren und Flattern. Doppelschlösser sorgen für Sicherheit, während das'
 ' wetterfeste Dach Schutz vor Regen und UV-Strahlen bietet. Ideal für 4-6 Hühner, erleichtert das'
 ' Hühner Freilaufgehege Füttern, Reinigen und Kontrollieren und ist für den täglichen Gebrauch'
 ' geeignet.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Bietet 4 m² Platz für 4-6 Hühner, um sich frei zu bewegen</p></li>'
 '<li><p>✔ Passt perfekt zu einem Holzstall für ein sicheres Zuhause</p></li>'
 '<li><p>✔ Doppelschlösser verhindern, dass clevere Hühner aus dem Gehege entkommen</p></li>'
 '<li><p>✔ Robuster, verzinkter Stahlrahmen mit kunststoffbeschichtetem Drahtgeflecht sorgt für die'
 ' Sicherheit der Hühner</p></li>'
 '<li><p>✔ Wetterfestes Dach aus 420D Oxford-Polyester schützt vor Sonne und Regen</p></li>'
 '<li><p>✔ Voll begehbares Design erleichtert das Füttern und Reinigen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Silber</p></li>'
 '<li><p>✔ Material: Verzinkter Stahl, 420D Oxford-Stoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 200L x 200B x 200H cm</p></li>'
 '<li><p>✔ Vordertür: 56B x 167H cm</p></li>'
 '<li><p>✔ Maschengröße: 4L x 2,5B cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Hühnergehege</p></li>'
 '<li><p>✔ 1 x Abdeckung</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 200L x 200B x 200H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Silber</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Verzinkter Stahl</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 18,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 198 × 23 × 16 cm</p></li></ul>'
)

K["19f566d8"] = (
 '<p>Suchen Sie eine elegante Lösung, um Ordnung zu schaffen? Das moderne Sideboard von bietet viel'
 ' Stauraum mit einer breiten Oberfläche, einer Schublade, zwei Schränken und zwei offenen Regalen –'
 ' ideal für Geschirr, Bücher oder tägliche Essentials. Das frische weiße Design des'
 ' Wohnzimmerschranks mit Holzoptik-Platte, Shaker-Türen und goldenen Griffen sorgt für eine'
 ' gemütliche, stilvolle Note. Perfekt für Wohnzimmer, Esszimmer, Flur oder Küche.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Geräumige Oberfläche zur Präsentation von Fotos und Dekorationen</p></li>'
 '<li><p>✔ Praktische Schublade verstaut kleine Gegenstände unsichtbar</p></li>'
 '<li><p>✔ Zwei Schränke verbergen Unordnung und sorgen für ein ordentliches Erscheinungsbild</p></li>'
 '<li><p>✔ Zwei offene Fächer des Sideboards für einfachen Zugriff auf häufig benutzte'
 ' Gegenstände</p></li>'
 '<li><p>✔ Das allseits passende, moderne Design eignet sich für Wohnzimmer, Esszimmer, Flur und'
 ' mehr</p></li>'
 '<li><p>✔ Anti-Kipp-Gurt des Aufbewahrungsschranks erhöht Sicherheit und Stabilität</p></li>'
 '<li><p>✔ Oberfläche mit Melaminbeschichtung für Kratzfestigkeit und einfache Reinigung</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß+Naturholz</p></li>'
 '<li><p>✔ Material: Spanplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 120B x 35T x 75,2H cm</p></li>'
 '<li><p>✔ Schubladen-Innenmaß: 24,1B x 29,1T x 8,5H cm</p></li>'
 '<li><p>✔ Offenes Fachmaß: 29B x 34,1T x 24,6H cm</p></li>'
 '<li><p>✔ Schrank-Innenmaß: 41,6B x 34,1T x 66,7H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 35 kg (gesamt), 10 kg (oben), 5 kg (Schublade/Fach)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Sideboard</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 120L x 35B x 75,2H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 27,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 132,5 × 48,2 × 16 cm</p></li></ul>'
)

K["5f730167"] = (
 '<p>Magnetische Heimtrainer-Workouts zu Hause wirken oft einsam und störend. Monotone Bewegungen'
 ' werden schnell zur Last, und Lärm stört Ihre Familie. Das klappbare Hometrainer Fahrrad schafft'
 ' Abhilfe: App-Anbindung für globale Touren, flexible Positionen für Ganzkörpertraining und ein'
 ' besonders leiser Betrieb des Ergometer Heimtrainers machen Fitness entspannt und'
 ' abwechslungsreich.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Verbinden Sie sich per Bluetooth mit Apps wie ZWIFT oder Kinomap für immersive,'
 ' wettbewerbsorientierte virtuelle Fahrten</p></li>'
 '<li><p>✔ Wechseln Sie zwischen aufrechter und liegender Position für ein vielseitiges'
 ' Ganzkörpertraining</p></li>'
 '<li><p>✔ Das Liegeergometer für Senioren enthält Widerstandsbänder, mit denen Sie Ihre Arme beim'
 ' Radfahren stärken können</p></li>'
 '<li><p>✔ Einstellbarer, 8-stufiger Magnetwiderstand des Heimtrainer Fahrrads ermöglicht die'
 ' individuelle Anpassung der Trainingsintensität</p></li>'
 '<li><p>✔ Gepolsterter, verstellbarer Sitz und Lenker sowie Pedalriemen sorgen für eine bequeme'
 ' Passform und unterstützen eine maximale Belastung von 120 kg</p></li>'
 '<li><p>✔ Zeit, Geschwindigkeit, Distanz, Kalorien und Herzfrequenz werden auf dem übersichtlichen'
 ' LCD-Display angezeigt</p></li>'
 '<li><p>✔ Zusammenklappbar auf 53,5 x 48 x 135 cm und mit Rollen für einfache Lagerung'
 ' ausgestattet</p></li>'
 '<li><p>✔ Teilweise vormontiert für eine einfache Einrichtung in ca. 30 Minuten</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Q195 Stahl</p></li>'
 '<li><p>✔ Gesamtabmessungen: 105L x 53,5B x 109H cm</p></li>'
 '<li><p>✔ Klappgröße: 53,5L x 48B x 135H cm</p></li>'
 '<li><p>✔ Sitzgröße: 25L x 22B cm</p></li>'
 '<li><p>✔ Sitzhöhe: 76-80 cm</p></li>'
 '<li><p>✔ Lenkerhöhe: 94-105 cm</p></li>'
 '<li><p>✔ LCD-Bildschirmgröße: 4,7L x 2,3B cm</p></li>'
 '<li><p>✔ Telefonhaltergröße: 12L x 12B cm</p></li>'
 '<li><p>✔ Schwungradgewicht: 1,5 kg</p></li>'
 '<li><p>✔ Geräuschpegel: 40 dB</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Klappbares Fitnessfahrrad</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 105L x 53,5B x 109H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Schwarz</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Stahl</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 20 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 98,5 × 39,5 × 25,5 cm</p></li></ul>'
)

K["041fa621"] = (
 '<p>Gestalten Sie Ihren Arbeitsbereich neu mit dem Computertisch, der industriellen Chic mit'
 ' praktischer Funktionalität kombiniert. Der Tisch bietet mit seiner rustikalen, braunen Oberfläche'
 ' Platz für mehrere Computer und eignet sich ideal als PC- oder Bürotisch. Zudem kann er leicht als'
 ' charmanten Esstisch oder kompakten Konferenztisch umfunktioniert werden, wobei die verstellbaren'
 ' Fußpads für Stabilität sorgen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Industrieller Stil und rustikal braune Oberfläche verbessern die Raumästhetik</p></li>'
 '<li><p>✔ Bietet Platz für Computermonitore jeder Größe</p></li>'
 '<li><p>✔ Dient als Esstisch und kleiner Konferenztisch, vielseitig einsetzbar</p></li>'
 '<li><p>✔ Das dreieckige Verbindungsdesign bietet zuverlässige Unterstützung für den langfristigen'
 ' Gebrauch</p></li>'
 '<li><p>✔ Verstellbare Fußpolster sorgen für Stabilität auf unebenen Böden</p></li>'
 '<li><p>✔ Hergestellt aus Spanplatten mit Melaminbeschichtung für Langlebigkeit</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Rustikal-Braun+Schwarz</p></li>'
 '<li><p>✔ Materialien: Spanplatte, Stahl</p></li>'
 '<li><p>✔ Gesamtabmessungen: 200L x 60B x 75H cm</p></li>'
 '<li><p>✔ Sitzplatzgröße: 185B x 71H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 60 kg (gesamt)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Computertisch</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 200L x 60B x 75H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Rustikal-Braun</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 27 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 113 × 68,5 × 20 cm</p></li></ul>'
)

K["cd473c5e"] = (
 '<p>Beleben Sie Ihr Schlafzimmer mit diesem modernen Set aus zwei Nachttischen. Jeder Sofatisch'
 ' verfügt über drei sanft gleitende Schubladen, die auf nur 0,12 m² Bodenfläche Ihre Nachtutensilien'
 ' bereithalten. Das grifflose, weiße Design der Nachtkommode verleiht jedem Raum eine klare, ruhige'
 ' Ausstrahlung. Diese funktionellen Nachttische bringen täglich mehr Ordnung und Stil in Ihr'
 ' Zuhause.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Set aus zwei Nachttischen für ein ausgewogenes, aufeinander abgestimmtes'
 ' Erscheinungsbild</p></li>'
 '<li><p>✔ Jeder Nachtschrank verfügt über drei Schubladen, um das Wesentliche griffbereit zu'
 ' halten</p></li>'
 '<li><p>✔ Platzsparendes Design des Nachtkästchens mit nur 0,12 ㎡ Grundfläche</p></li>'
 '<li><p>✔ Grifffreie Front für eine saubere, minimalistische Note</p></li>'
 '<li><p>✔ Die komplett weiße Oberfläche mit griffloser Vorderseite verleiht einen klaren,'
 ' minimalistischen Touch</p></li>'
 '<li><p>✔ Melaminoberfläche der Nachtkommode ist glatt und kratzfest für leichte Reinigung</p></li>'
 '<li><p>✔ Kippsicherungen erhöhen die Stabilität und Sicherheit</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: MDF</p></li>'
 '<li><p>✔ Gesamtabmessungen: 40B x 30T x 59,5H cm</p></li>'
 '<li><p>✔ Innengröße der Schublade: 32,5B x 24T x 6,5H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 30 kg (gesamt), 5 kg (Schublade)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 2 x Nachttisch</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 40L x 30B x 59,5H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 24,8 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 66,5 × 72 × 16,5 cm</p></li></ul>'
)

K["d5229703"] = (
 '<p>So spaßig kann Lernen sein! Mit unseren großen, weichen Spielklötzen schaffen Sie eine sichere'
 ' und farbenfrohe Spielumgebung für Kinder von 1 bis 3 Jahren. Die elf verschiedenen, weich'
 ' gepolsterten Spielblöcke regen die Fantasie und Kreativität der Kinder an, während Ihre kleinen'
 ' Entdecker/innen spielerisch ihr Farb- und Raumverständnis, die Motorik und die'
 ' Hand-Augenkoordination trainieren. Sehr praktisch: Die Klötze lassen sich bequem mit einem'
 ' feuchten Tuch abwischen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Enthält elf verschiedene Schaumstoffklötze, die die Fantasie und Kreativität der Kinder'
 ' anregen</p></li>'
 '<li><p>✔ Das weiche Spielset umfasst zwei Halbzylinder, zwei kleine Dreiecke, ein großes Dreieck,'
 ' einen kleinen Halbzylinder, zwei Rechtecke und drei Würfel</p></li>'
 '<li><p>✔ Lässt sich die Softbausteine leicht mit einer milden Seifen- und Wasserlösung'
 ' abwischen</p></li>'
 '<li><p>✔ Kein lästiger Zusammenbau erforderlich</p></li>'
 '<li><p>✔ Empfohlenes Alter: 1-3 Jahre</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Bunt</p></li>'
 '<li><p>✔ Material: Kunstleder, EPE</p></li>'
 '<li><p>✔ Quader: 25L x 25B x 50H cm</p></li>'
 '<li><p>✔ Würfel: 25L x 25B x 25H cm</p></li>'
 '<li><p>✔ Kleines rechtes Dreieck: 25L x 25B x 25H cm</p></li>'
 '<li><p>✔ Großes rechtes Dreieck: 50L x 50B x 25H cm</p></li>'
 '<li><p>✔ Kleiner Zylinder: Ø25 x 25L cm</p></li>'
 '<li><p>✔ Großer Zylinder: Ø25 x 50L cm</p></li>'
 '<li><p>✔ Empfohlenes Alter: 1-3 Jahre alt</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 11 x Bauklötze</p></li>'
 '<li><p>✔ 1 x Gebrauchsanweisung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 25L x 25B x 50H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Mehrfarbig</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Kunstleder</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 9 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 77,5 × 54,5 × 52 cm</p></li></ul>'
)

K["89b2a551"] = (
 '<p>Entfesseln Sie die kulinarische Kreativität Ihres Kindes mit dem Spielküchen-Set! Diese'
 ' beeindruckende Spielküche bietet einen Herd mit realistischen Geräuschen und Lichtern, einen'
 ' Kühlschrank, eine Eismaschine und eine Mikrowelle – für endlosen Spielspaß. Der integrierte'
 ' Kaffeeautomat der Kinderküche sorgt für zauberhafte Brunch-Momente. Besonders authentisch wird das'
 ' Kochen durch das Spülbecken mit Wasserkreislaufsystem – ein unverzichtbares Geschenk für kleine'
 ' Köchinnen und Köche!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Beleben Sie die kulinarische Kreativität Ihres Kindes mit der Spielzeugküche für'
 ' Kinder</p></li>'
 '<li><p>✔ Herd mit realistischen Geräuschen und Lichtern für authentische Kocherlebnisse</p></li>'
 '<li><p>✔ Enthält Kühlschrank, Eiswürfelmaschine, Mikrowelle und Kaffeemaschine für endlosen'
 ' Spielspaß</p></li>'
 '<li><p>✔ Küchenspüle mit zirkulierendem Wassersystem für realistische Spielmöglichkeiten</p></li>'
 '<li><p>✔ Fünfteiliges Kochgeschirrset der Puppenküche mit Edelstahl-Zubehör</p></li>'
 '<li><p>✔ Viel Stauraum mit Regalen und Schränken zur Organisation von Spielzeug</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: MDF</p></li>'
 '<li><p>✔ Gesamtabmessungen: 80L x 29,7B x 100,9H cm</p></li>'
 '<li><p>✔ Kühlschrank: 25L x 27,9B x 45H cm (Oben), 25,1L x 27,8B x 48,2H cm (Unten)</p></li>'
 '<li><p>✔ Untere Ablage: 25,2L x 27,8B x 27,7H cm / 19,7H cm</p></li>'
 '<li><p>✔ Tischplatte: 52,5L x 28B x 29,6H cm</p></li>'
 '<li><p>✔ Höhe der Tischplatte: 55,2 cm</p></li>'
 '<li><p>✔ Geeignetes Alter: 3+ Jahre</p></li>'
 '<li><p>✔ Empfohlenes Alter: 3-8 Jahre</p></li>'
 '<li><p>✔ Hinweis: 4 x AAA-Batterien werden für Herd und Spüle benötigt (nicht enthalten)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Spielküche</p></li>'
 '<li><p>✔ 5 x Edelstahltopf</p></li>'
 '<li><p>✔ 2 x Kaffeetasse</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 80L x 29,7B x 100,9H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 19,4 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 100 × 39 × 19 cm</p></li></ul>'
)

K["10957741"] = (
 '<p>Entfalten Sie die Fantasie Ihres Kindes mit der Spielküche – ein unverzichtbares Highlight für'
 ' jedes Kinderzimmer! Diese Kinderküche bietet ein 14-teiliges Zubehör, das die Kreativität anregt'
 ' und stundenlangen Spielspaß garantiert. Es fördert nicht nur die Feinmotorik, sondern auch'
 ' kognitive, soziale und mathematische Fähigkeiten. Mit einem funktionierenden Wasserspender, einer'
 ' befüllbaren Spüle und einer öffnenden Tür wird die Kinderküche besonders bunt und realistisch.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Einfaches Design der Kinderküche, das jedes Kind lieben wird</p></li>'
 '<li><p>✔ Mit elektronischem Wasserspender, aufklappbarer Tür und befüllbarem Waschbecken</p></li>'
 '<li><p>✔ Langlebiges MDF-Material der Spielküche mit sicheren, abgerundeten Kanten</p></li>'
 '<li><p>✔ Fördert Kreativität sowie Feinmotorik, kognitive und mathematische Fähigkeiten</p></li>'
 '<li><p>✔ Benötigt 2 x AA-Batterien, nicht enthalten</p></li>'
 '<li><p>✔ Geeignet für Kinder ab 3 Jahren</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Material: Kiefernholz, MDF</p></li>'
 '<li><p>✔ Farbe: Weiß+Silber</p></li>'
 '<li><p>✔ Gesamtabmessungen: 86L x 64B x 84,5H cm</p></li>'
 '<li><p>✔ Größe der oberen Schranktür: 23,5B x 35H cm(rechter Kühlschrank)</p></li>'
 '<li><p>✔ Größe der unteren Tür: 23,5B x 20H cm(rechter Kühlschrank)</p></li>'
 '<li><p>✔ Größe der anderen Schranktüren: 23,5B x 30H cm</p></li>'
 '<li><p>✔ Größe des Spülbeckens: 21L x 15B x 7H cm</p></li>'
 '<li><p>✔ Größe der Dunstabzugshaube: 20L x 11,5B x 5H cm</p></li>'
 '<li><p>✔ Größe der Mikrowellentür: 28B x 12,5H cm</p></li>'
 '<li><p>✔ Batterien: 2 x AA-Batterien (nicht enthalten)</p></li>'
 '<li><p>✔ Alter: 3+ Jahre</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Spielküche mit Zubehör</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 86L x 64B x 84,5H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 19,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 85,5 × 43 × 20 cm</p></li></ul>'
)

json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)


def summa(s):
    h = 0
    for c in s:
        h = (h * 31 + (ord(c) & 0xFFFF)) % 1000000007
    return h


for k, v in K.items():
    print("%s\t%d\t%d" % (k, summa(v), len(v)))
