#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska kalltexterna.

☠️ FILEN AR EN AVSKRIFT och far darfor inte litas pa. Kor
`kontrollera-kalla` (h*31 per produkt, server-side mot skarpa V3)
innan en enda grind korts — samma ordning som N26–N31. N27:s forsta
korning gav 7 av 8 och fallde ett akta transkriberingsfel med RATT
teckenantal men fel summa. Det ar SUMMAN som avgor, inte langden.
"""
import io, json, collections

K = collections.OrderedDict()

K["40fb1b24"] = (
 '<p>Nicht nur Ihr Fernseher kann mit Ambilights tolle Atmosphäre schaffen. Unser Wandkamin ist mit schönen'
 ' LEDs ein echter Konkurrent! Diese können Sie ganz bequem per Fernbedienung in verschiedenen Farben'
 ' zuschalten. Die Feueranimation ist hinter der eleganten Glasfront untergebracht. Das lodernde Feuer'
 ' erhellt somit den ganzen Raum und verleiht ihm ein romantisches Flair. So wird gemütliches Zurücklehnen'
 ' ein echtes Erlebnis.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Moderne und schöne Optik</p></li>'
 '<li><p>✔ LED Flamme 2-stufig dimmbar</p></li>'
 '<li><p>✔ 2 Heizstufen wählbar, 1000/2000W</p></li>'
 '<li><p>✔ Mit insgesamt 18 LEDs als Hintergrundbeleuchtung, 7 Farben veränderbar</p></li>'
 '<li><p>✔ Thermo-Abschaltung zum Schutz vor Überhitzen</p></li>'
 '<li><p>✔ Ein-/Ausschalter an der Oberseite</p></li>'
 '<li><p>✔ Mit Kies</p></li>'
 '<li><p>✔ Wandmontage</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Material: Metall und Sicherheitsglas</p></li>'
 '<li><p>✔ Maße: 89,2 x 13,5 x 48 cm (L x B X H)</p></li>'
 '<li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Leistung: 1000/2000W</p></li>'
 '<li><p>✔ Spannung: 220 - 240 V</p></li>'
 '<li><p>✔ Leitung: 1,5 m</p></li>'
 '<li><p>✔ Kabellänge: 1,6 m</p></li>'
 '<li><p>✔ Hinweis: Nur für die Wandmontage vorgesehen. Eine versenkte Montage wird nicht empfohlen.</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔1 x Elektrokamin</p></li>'
 '<li><p>✔Inkl. Fernbedienung (2 x AA Batterie nicht enthalten)</p></li>'
 '<li><p>✔Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> Modell7/88,5 x 13,5 x 56cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Schwarz</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Metall und Sicherheitsglas</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 16,6 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 102 × 20 × 58,5 cm</p></li></ul>'
)

K["c6f8a0f1"] = (
 '<p>Verwandeln Sie Ihren Garten in ein zauberhaftes Winterwunderland mit der Weihnachtsbeleuchtung von .'
 ' Unsere LED Rentierfamilie, geschmückt mit leuchtend roten Schleifen und schimmerndem Stoff, sorgt für eine'
 ' warme, einladende Atmosphäre dank der wunderschönen LEDs. Ideal für den Garten, die Terrasse oder den Hof,'
 ' schafft diese Weihnachtsbeleuchtung überall eine festliche Stimmung. Lassen Sie sich von der Magie der'
 ' Feiertage verzaubern!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dreiteilige Weihnachtsbeleuchtung: niedliche Rentierfamilie</p></li>'
 '<li><p>✔ Rote Schleifen und goldglänzender Stoff bieten einen wunderschönen Anblick</p></li>'
 '<li><p>✔ Warmweiße LEDs (Dauerlicht/Blinken) unter dem transparenten Stoff erzeugen einen fesselnden'
 ' Glanz</p></li>'
 '<li><p>✔ Pulverbeschichteter Stahlrahmen der Weihnachtsbeleuchtung widersteht Rost und Abnutzung</p></li>'
 '<li><p>✔ Inklusive 12 Erdspießen und 15 Kabelbindern für Stabilität</p></li>'
 '<li><p>✔ Die Wasserdichtigkeit gemäß IP44 gewährleistet, dass sie leichtem Regen und Schneefall standhält'
 ' (bei Nichtgebrauch im Innenbereich aufbewahren)</p></li>'
 '<li><p>✔ Einfache Montage ermöglicht schnellen Aufbau</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Silber</p></li>'
 '<li><p>✔ Material: Stahl, Polyester</p></li>'
 '<li><p>✔ Typ: 3-teilige Rentierfamilie</p></li>'
 '<li><p>✔ Rentierabmessungen: 64L x 37B x 134H cm (größtes), 71L x 23B x 112H cm (mittel), 45L x 17B x'
 ' 70H cm (kleinstes)</p></li>'
 '<li><p>✔ LED-Anzahl: 283 (254 dauerhaft an, 29 blinkend)</p></li>'
 '<li><p>✔ Jede LED: DC 3V, 0,012W</p></li>'
 '<li><p>✔ Kabellänge: 5 m</p></li>'
 '<li><p>✔ Eingang: AC 220-240V, 50/60Hz, 0,5 A</p></li>'
 '<li><p>✔ Ausgang: DC 5V, 10W, 2A</p></li>'
 '<li><p>✔ Zertifizierung: IP44</p></li>'
 '<li><p>✔ Hinweis: 1, Bitte nicht vor der Montage am Stromnetz anschließen</p></li>'
 '<li><p>2, Nicht bei starkem Regen, Schnee oder Wind verwenden</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Weihnachsbeleuchtung: Rentierfamilie</p></li>'
 '<li><p>✔ 12 x Erdspieß</p></li>'
 '<li><p>✔ 15 x Kabelbinder</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 64L x 37B x 134H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Gold</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Stahl</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 5,7 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 57 × 29 × 61 cm</p></li></ul>'
)

K["8f95113c"] = (
 '<p>Genießen Sie angenehme Nächte mit der Matratze: 4 cm Gel-Memory-Schaumstoff und atmungsaktiver'
 ' 350 g/m² Bezug sorgen für optimale Temperatur. Die 16 cm grüntee-angereicherte Basisschaumstoff-Schicht'
 ' unterstützt Ihre Wirbelsäule, reduziert Druckstellen und bietet Frische. Waschbarer Bezug und'
 ' Anti-Rutsch-Unterseite für gesunden, ruhigen Schlaf.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 4 cm Gel-Schaumstoff in dieser Matratze leitet Wärme ab und sorgt für kühleren'
 ' Schlafkomfort</p></li>'
 '<li><p>✔ Hochwertiger 350 gsm gestrickter Stoff fördert die Luftzirkulation, um Körperwärme effektiv'
 ' abzuleiten</p></li>'
 '<li><p>✔ Natürlicher, mit grünem Tee angereicherter Basisschaumstoff bietet festen Halt und neutralisiert'
 ' Gerüche</p></li>'
 '<li><p>✔ 16 cm hochdichter Schaumstoff bietet feste Unterstützung und richtet die Wirbelsäule bequem aus,'
 ' was diese Matratze besonders langlebig macht</p></li>'
 '<li><p>✔ Abnehmbarer Bezug mit 3-Wege-Reißverschluss ermöglicht eine einfache Reinigung von Staub und'
 ' Flecken</p></li>'
 '<li><p>✔ Rutschfeste Unterseite hält die Matratze stabil und sorgt für einen ruhigeren Schlaf</p></li>'
 '<li><p>✔ Materialien nach CertiPUR-US gewährleisten Sicherheit und einen zuverlässigen Schlaf</p></li>'
 '<li><p>✔ Lassen Sie der Matratze bis zu 72 Stunden Zeit, um sich vollständig in ihre ursprüngliche Form'
 ' auszudehnen</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß+Grau</p></li>'
 '<li><p>✔ Material: Strickstoff (100 % Polyester), Antirutschstoff, Gel-Memory-Schaumstoff,'
 ' Grüner-Tee-Normal-Schaumstoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 200L x 140B x 20H cm</p></li>'
 '<li><p>✔ Zertifizierung: CertiPur US</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Doppelmatratze;</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 140 x 200 cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Grau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Gel-Schaum/Polyester</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 20,19 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 32 × 32 × 150 cm</p></li></ul>'
)

K["41b2bc81"] = (
 '<p>Unbequeme Sitzgelegenheiten können Familienessen verderben, unruhige Gäste und Rückenschmerzen'
 ' verursachen. Die Esszimmerstühle bieten gepolsterten ergonomischen Halt sowie atmungsaktiven,'
 ' hautfreundlichen Stoff. Die Beine aus massivem Gummibaumholz sorgen für stabile, wackelfreie'
 ' Standfestigkeit, während das minimalistische Design Ihre Einrichtung aufwertet. Entspannen Sie sich und'
 ' schaffen Sie besondere Momente mit diesen zwei Küchenstühlen, die für Komfort und Geselligkeit entwickelt'
 ' wurden.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Die Küchenstühle sind mit Originalschaum mit hoher Rückstellkraft gepolstert, der sanften und'
 ' langanhaltenden Komfort für den täglichen Gebrauch bietet</p></li>'
 '<li><p>✔ Die geschwungene Rückenlehne umschließt den Körper und fördert eine korrekte Haltung sowie'
 ' entspanntes Sitzen</p></li>'
 '<li><p>✔ Der Leinenoptik-Stoff ist atmungsaktiv und verschleißfest für den täglichen Gebrauch</p></li>'
 '<li><p>✔ Der dem OEKO-TEX STANDARD 100 entsprechende Bezug garantiert Sicherheit für den'
 ' Familiengebrauch</p></li>'
 '<li><p>✔ Die Esszimmerstühle verfügen über Beine aus Gummibaumholz und einen robusten Rahmen aus Sperrholz,'
 ' die eine stabile Unterstützung bis zu 120 kg bieten</p></li>'
 '<li><p>✔ Die verstellbaren Füße schützen den Boden und verbessern die Stabilität</p></li>'
 '<li><p>✔ Die Esszimmerstühle haben ein minimalistisches und kompaktes Design, das sich perfekt an'
 ' Esszimmer, Wohnzimmer oder gemütliche Leseecken anpasst</p></li>'
 '<li><p>✔ Die schnelle Montage spart Zeit dank klarer Anleitung und gekennzeichneter Teile</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Creme</p></li>'
 '<li><p>✔ Material: Stoff in Leinenoptik (100% Polyester), Originalschaum, Gummibaumholz, Sperrholz</p></li>'
 '<li><p>✔ Gesamtabmessungen: 46L x 52T x 76H cm</p></li>'
 '<li><p>✔ Sitzmaße: 46L x 43T x 48H cm</p></li>'
 '<li><p>✔ Rückenlehnenmaße: 46L x 34H cm</p></li>'
 '<li><p>✔ Stärke: 7 cm (Sitz), 3,5 cm (Rückenlehne)</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 2 x Esszimmerstühle</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 46 x 52 x 76 cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Creme</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Stoff (Leinenoptik), Gummibaumholz</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 12,4 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 56 × 42 × 49,5 cm</p></li></ul>'
)

K["6ab7b3b0"] = (
 '<p>Optimieren Sie Ihr Heimtraining mit dem Heimtrainer Fahrrad. Kalorien verbrennen oder Herzgesundheit'
 ' fördern? Dieser Ergometer Heimtrainer passt sich flexibel Ihrer Routine an. Dank der verbesserten'
 ' Bluetooth-Funktion verbinden Sie sich mit Apps wie KINOMAP und ZWIFT für interaktive Workouts. Das'
 ' geräuscharme magnetische Widerstandssystem mit 8 Stufen ermöglicht vom sanften Warm-up bis zum intensiven'
 ' Cardio alles – ohne andere zu stören.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Verbesserte Bluetooth-Konnektivität synchronisiert sich mit Apps wie KINOMAP und ZWIFT für'
 ' interaktives Training</p></li>'
 '<li><p>✔ 8-stufiger manueller magnetischer Widerstand des Hometrainer Fahrrads ermöglicht einfaches'
 ' Anpassen der Trainingsintensität</p></li>'
 '<li><p>✔ Leises, riemengetriebenes System sorgt für eine reibungslose Fahrt, ohne andere zu stören'
 ' (≈60 dB)</p></li>'
 '<li><p>✔ LCD-Monitor verfolgt Zeit, Geschwindigkeit, Distanz, Kalorien, Herzfrequenz und'
 ' Kilometerzähler</p></li>'
 '<li><p>✔ 9-stufig höhenverstellbarer Sitz (65–91 cm) passt für Nutzer von 120–195 cm</p></li>'
 '<li><p>✔ Strukturierte, rutschfeste Pedale mit verstellbaren Riemen bieten sicheren und stabilen'
 ' Halt</p></li>'
 '<li><p>✔ H-förmiger verstärkter Stahlrahmen des Hometrainer Fahrrads trägt bis zu 120 kg für ein'
 ' zuverlässiges Training</p></li>'
 '<li><p>✔ Eingebaute Transportrollen ermöglichen einfache Bewegung und platzsparende Aufbewahrung</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 86L x 51B x 128H cm</p></li>'
 '<li><p>✔ Sitzgröße: 26L x 22B cm</p></li>'
 '<li><p>✔ Sitzhöhe: 65-91 cm</p></li>'
 '<li><p>✔ Lenkerhöhe: 127 cm</p></li>'
 '<li><p>✔ Schwungradgewicht: 4 kg</p></li>'
 '<li><p>✔ Geräuschpegel: 60 dB</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Heimtrainer</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 86L x 51B x 128H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Schwarz</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 21 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 67 × 28,5 × 54,5 cm</p></li></ul>'
)

K["b42b4802"] = (
 '<p>Kämpfen Sie mit einem engen, unübersichtlichen Arbeitsbereich? Ein Arbeitstisch, der sich nicht Ihren'
 ' Bedürfnissen anpasst, kann frustrierend sein. Der L-förmige Schreibtisch mit Regal, der sich 360° drehen'
 ' lässt, passt perfekt in jede Ecke oder an jede Wand. Ausgestattet mit Schränken und Regalen, organisiert'
 ' dieser Bürotisch Ihre Utensilien und schafft einen auf Sie zugeschnittenen, effektiven Bereich, der Ihren'
 ' Fokus verbessert und das Potential Ihres Raumes erhöht.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Der Ecktisch verfügt über ein 360° drehbares Design, das problemlos zwischen L-förmiger, gerader'
 ' oder gefalteter Anordnung wechselt</p></li>'
 '<li><p>✔ Der Computertisch kombiniert zwei Schränke und zwei offene Regale, um Ihren Arbeitsbereich'
 ' ordentlich und organisiert zu halten</p></li>'
 '<li><p>✔ Der Arbeitstisch trägt bis zu 100 kg insgesamt, was eine stabile und sichere Einrichtung'
 ' gewährleistet</p></li>'
 '<li><p>✔ Stahlbeine mit verstellbaren Füßen bieten ein stabiles Arbeitserlebnis</p></li>'
 '<li><p>✔ Modernes Design des Schreibtisches mit Stauraum ergänzt elegant verschiedene Einrichtungsstile zu'
 ' Hause</p></li>'
 '<li><p>✔ Melaminoberfläche ist kratzfest für einfache Reinigung</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß, Naturholz</p></li>'
 '<li><p>✔ Materialien: Spanplatte, MDF</p></li>'
 '<li><p>✔ Gesamtabmessungen: 105B x 85T x 75H cm (L-förmig), 150B x 40T x 75H cm (gerade), 100B x 40T x'
 ' 75H cm (gefaltet)</p></li>'
 '<li><p>✔ Tischplattengröße: 100L x 40B cm</p></li>'
 '<li><p>✔ Knieraumgröße: 60B x 74H cm</p></li>'
 '<li><p>✔ Schrankinnenmaß: 35,6B x 38,5T x 33,7H cm</p></li>'
 '<li><p>✔ Offene Regalgröße: 40B x 40T x 33,7H cm</p></li>'
 '<li><p>✔ Maximale Belastung: 50 kg (Tischplatte), 10 kg (Regal/Schrank), 100 kg (gesamt)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x L-förmiger Computertisch</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 150L x 40B x 75H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 26 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 115 × 50 × 18 cm</p></li></ul>'
)

K["2808fff3"] = (
 '<p>Verschönern Sie Ihr Wohnzimmer und Ihren Unterhaltungsbereich mit diesem charaktervollen TV-Lowboard von'
 ' . Die Kombination des TV Sideboards aus rustikaler, industrieller Ästhetik und dem praktischen Design mit'
 ' zwei Gleittüren wird Ihr Ambiente mit Geschmack und Charakter bereichern. Ideal geeignet für Fernsehgeräte'
 ' bis zu 60 Zoll und ausgestattet mit 6 Fächern, bietet der Fernsehschrank reichlich Platz für'
 ' Spielekonsolen, Blu-rays, Bücher und unterschiedlichste Dekorationselemente.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Für Fernseher bis zu 60"</p></li>'
 '<li><p>✔ 6 Fächer des TV Boards bieten reichlich Platz für verschiedene Unterhaltungsgeräte und'
 ' Dekoelemente</p></li>'
 '<li><p>✔ Stabiler Stahlrahmen und lackierte, pflegeleichte Oberfläche</p></li>'
 '<li><p>✔ Kann im Wohnzimmer, Gamingraum oder Schlafzimmer verwendet werden</p></li>'
 '<li><p>✔ Praktische und hochbequeme Schiebetüren mit schwarzen Führungsschienen</p></li>'
 '<li><p>✔ 6 Kabelöffnungen der TV Kommode sorgen für eine ordentliche Kabelführung</p></li>'
 '<li><p>✔ Fußkappen der TV Bank schützen Ihren Boden vor Kratzern</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Rustikales Braun+Schwarz</p></li>'
 '<li><p>✔ Material: Spanplatte, MDF, Stahl</p></li>'
 '<li><p>✔ Gesamtmaße: 120L x 40B x 54H cm</p></li>'
 '<li><p>✔ Türmaße: 29B x 35,7H cm</p></li>'
 '<li><p>✔ Maße der äußeren Schrankfächer: 27,7L x 33,2B x 43H cm</p></li>'
 '<li><p>✔ Maße des Schrankfachs: 55,5L x 33,2B x 43H cm(zentral)</p></li>'
 '<li><p>✔ Maße der Kabelöffnung: Ø5,3 cm</p></li>'
 '<li><p>✔ Abstand zum Boden: 6 cm</p></li>'
 '<li><p>✔ Max. Belastung: 50 kg (insgesamt), 20 kg (Tischplatte), 5 kg (Regal), 10 kg (Bodenplatte)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x TV-Bank</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 120L x 40B x 54H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Rustikal Braun</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Spanplatte</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 27 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 131,5 × 48 × 15 cm</p></li></ul>'
)

K["db1d494f"] = (
 '<p>Steigern Sie Ihre sportlichen Fähigkeiten mit dem Basketballkorb! Entwickelt für Langlebigkeit, bietet'
 ' diese an der Wand befestigte Konstruktion des Indoor Basketballkorbs eine 110 x 75 cm große, bruchsichere'
 ' Rückwand und einen federbelasteten Korb, der sich auch bei Slam Dunks flexibel verhält. Perfekt für'
 ' Beton-, Ziegel- oder Holzwände in Garagen, Innenräumen oder auf dem Hof.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Sicher an Zement-, Ziegel- oder Massivholzwänden montierbar</p></li>'
 '<li><p>✔ 110 x 75 cm bruchsichere Rückwand des Indoor Basketballkorbs hält intensiven Spielen stand</p></li>'
 '<li><p>✔ Federaktivierter Basketballkorb biegt sich beim Dunking</p></li>'
 '<li><p>✔ Stahlkorb mit reißfestem Netz garantiert Langlebigkeit</p></li>'
 '<li><p>✔ Montage erleichtert durch mitgelieferte Schrauben</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Materialien: Stahl, Hochfestes Kunststoff</p></li>'
 '<li><p>✔ Rückwandabmessungen: 110L x 75H cm</p></li>'
 '<li><p>✔ Korbmaße: Ø45 cm</p></li>'
 '<li><p>✔ Abstand der Halterung: (von der Wand)23 cm</p></li>'
 '<li><p>✔ Abstand der Montagelöcher: 113B x 23H cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Wandmontierter Basketballkorb</p></li>'
 '<li><p>✔ 1 x Schraubenset</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 110L x 23B x 75H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Schwarz</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Stahl</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 13,3 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 113 × 12,5 × 80 cm</p></li></ul>'
)

json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)


def summa(s):
    h = 0
    for c in s:
        h = (h * 31 + (ord(c) & 0xFFFF)) % 1000000007
    return h


for k, v in K.items():
    print("%s\t%d\t%d" % (k, summa(v), len(v)))
