#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska kalltexterna.

☠️ FILEN AR EN AVSKRIFT och far darfor inte litas pa. Kor
`kontrollera-kalla` (h*31 per produkt, server-side mot skarpa V3)
innan en enda grind korts — samma ordning som N26 och N27. N27:s forsta
korning gav 7 av 8 och fallde ett akta transkriberingsfel med RATT
teckenantal men fel summa.
"""
import io, json, collections

K = collections.OrderedDict()

K["01d8e819"] = (
 '<p>Verwandeln Sie Ihr Zuhause in einen abenteuerlichen Spielplatz mit dem 3-in-1 Indoor Klettergerüst!'
 ' Dieses vielseitige Montessori-Klettergerüst bietet eine verstellbare Kletterleiter sowie eine wendbare'
 ' Rutsche, die gleichzeitig als Kletterwand dient. Aus sicherem, glattem Mehrschicht-Pinienholz gefertigt,'
 ' ist dieses Kletterdreieck faltbar und lässt sich mühelos verstauen. Ideal für aktive Kinder, fördert es'
 ' nicht nur die motorischen Fähigkeiten, sondern sorgt auch für stundenlangen Spielspaß.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 3-in-1 Design des Klettergerüsts fördert abwechslungsreichen Spielspaß und Freude</p></li>'
 '<li><p>✔ Enthält eine vierstufige Kletterleiter und eine Rutsche für aktives Spielen</p></li>'
 '<li><p>✔ Rutsche des Klettergerüsts kann auch als Kletterwand genutzt werden für dynamischen Einsatz</p></li>'
 '<li><p>✔ Hergestellt aus mehrschichtigem Kiefernholz mit glatter Oberfläche für Sicherheit</p></li>'
 '<li><p>✔ Faltbares Design des Kletterdreiecks ermöglicht einfache Lagerung und verstellbare Spielwinkel</p></li>'
 '<li><p>✔ Speziell für sicheres und unterhaltsames Spielen in Innenräumen konzipiert</p></li>'
 '<li><p>✔ Unterstützt bis zu 50 kg, geeignet für zwei Kinder im Alter von 1,5 bis 4 Jahren</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Mehrfarbig</p></li>'
 '<li><p>✔ Material: Kiefernholz, Mehrschichtenplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 175L x 70B x 89H cm</p></li>'
 '<li><p>✔ Klettergerüst: 213L x 70B x 7H cm (Fliesengröße)</p></li>'
 '<li><p>✔ Rutsche: 114L x 43,5B cm</p></li>'
 '<li><p>✔ Klappmaß: 70L x 53B x 30H cm</p></li>'
 '<li><p>✔ Maximale Belastung: 50 kg</p></li>'
 '<li><p>✔ Standardalter: 18+ Monate</p></li>'
 '<li><p>✔ Empfohlenes Alter: 18-48 Monate</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Klettergerüst für Kinder</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 175L x 70B cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Mehrfarbig</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holz</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 18,1 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 123 × 51,5 × 16,5 cm</p></li></ul>'
)

K["a9c2bfd8"] = (
 '<p>Dieses Set aus 12 verzinkten Trapezblechen von eignet sich ideal, um bestimmte Bereiche gezielt zu'
 ' reparieren oder zu verstärken. Die aus robustem Stahl gefertigten Dachblechplatten bieten zuverlässigen'
 ' Schutz, wo er benötigt wird. Dank der vorgebohrten Löcher lassen sich die Dachplatten einfach montieren'
 ' und bei Bedarf auf das gewünschte Maß zuschneiden.</p>'
 '<h3>Beschreibung:</h3><ul><li><p>✔ Enthält 12 Dachplatten</p></li>'
 '<li><p>✔ Vielseitig einsetzbar: als äußere Verkleidung für Wand- und Dachteile bei Schuppen, Carports,'
 ' Gewächshäusern oder Garagen</p></li>'
 '<li><p>✔ Vorgebohrte Löcher der Dachplatten für eine schnelle und einfache Montage</p></li>'
 '<li><p>✔ Dachplatten können auf das gewünschte Maß zugeschnitten werden</p></li>'
 '<li><p>✔ Wetterfest und pflegeleicht</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Naturholz</p></li>'
 '<li><p>✔ Material: Farbbeschichteter Stahl</p></li>'
 '<li><p>✔ Maße jedes Panels: 129L x 45B cm</p></li>'
 '<li><p>✔ Stärke: 0,25 mm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 12 x verzinkte Stahlplatten;</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 129cm x 45cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Naturholz (naturbelassenes Holz)</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Stahl</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 17,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 138 × 50 × 5 cm</p></li></ul>'
)

K["c804d1b7"] = (
 '<p>Haben Sie Schwierigkeiten mit unebenen Spaziergängen, die Ihren pelzigen Freund belasten, oder lassen'
 ' Sie ihn aus Bequemlichkeit zu Hause? Dieser -Hundewagen bietet die Lösung. Er gleitet mühelos über jedes'
 ' Gelände, von Parks bis zu Gehwegen, und sorgt für eine stabile und angenehme Fahrt. Mit der'
 ' Ein-Klick-Faltfunktion und dem geräumigen Innenraum sind spontane, komfortable Abenteuer immer möglich,'
 ' um gemeinsame Momente zu genießen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Lässt sich in Sekundenschnelle mit einem Ein-Klick-Mechanismus für mühelosen Transport und'
 ' einfache Lagerung zusammenklappen</p></li>'
 '<li><p>✔ Große geländegängige Räder und eine Doppelbremse sorgen für eine reibungslose, stabile Fahrt</p></li>'
 '<li><p>✔ Geräumiges Innenleben mit Panoramafenstern aus Netzgewebe sorgt für Komfort und optimale'
 ' Belüftung</p></li>'
 '<li><p>✔ Niedriger Einstieg hinten und zwei Sicherheitsleinen ermöglichen einen einfachen und sicheren'
 ' Zugang</p></li>'
 '<li><p>✔ Hergestellt aus robustem 600D Oxford-Stoff, der Verschleiß und Kratzer widersteht</p></li>'
 '<li><p>✔ Klettverschluss am Verdeck ermöglicht schnellen, einhändigen Zugriff auf Ihr Haustier</p></li>'
 '<li><p>✔ Verfügt über eine große Rückentasche, in der alle wichtigen Dinge griffbereit bleiben</p></li>'
 '<li><p>✔ Geeignet für mittelgroße Hunde bis zu 20 kg und einer Körperlänge von maximal 51 cm</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Grau+Weiß+Schwarz</p></li>'
 '<li><p>✔ Material: Oxford-Gewebe, Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 92L x 63B x 95H cm</p></li>'
 '<li><p>✔ Faltmaße: 91L x 63B x 39H cm</p></li>'
 '<li><p>✔ Interne Kabinengröße: 73L x 45B x 63H cm</p></li>'
 '<li><p>✔ Kissengröße: 72L x 43B cm</p></li>'
 '<li><p>✔ Vorderradgröße: Ø17 cm</p></li>'
 '<li><p>✔ Hinterradgröße: Ø24,5 cm</p></li>'
 '<li><p>✔ Maximale Belastung: 20 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Hundebuggy</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 92cm x 63cm x 95cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Grau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Polyester/Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 11,2 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 80,5 × 22 × 51 cm</p></li></ul>'
)

K["cb31a581"] = (
 '<p>Wenn spontan Gäste kommen, fehlt schnell ein Sitzplatz. Das stapelbare 4er-Hocker-Set von schafft'
 ' sofort vier Plätze, ohne die Küche vollzustellen. Dank montagefreier Nutzung ist jeder Hocker direkt'
 ' bereit. Die 6 cm gepolsterte, atmungsaktive Sitzfläche des Küchenhockers sorgt für Komfort beim Essen,'
 ' Plaudern oder Vorbereiten. So wirken kleine Räume entspannter, einladender und leichter zu'
 ' organisieren.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dieses Set aus 4 Hockern fügt sich mühelos in Esszimmer, Küchen und Wohnzimmer ein</p></li>'
 '<li><p>✔ Eine 6 cm dick gepolsterte Sitzfläche mit Schaumstofffüllung bietet auf jedem Hocker bequemen'
 ' Sitzkomfort</p></li>'
 '<li><p>✔ Der Stoff in Leinenoptik ist bei jedem Küchenhocker atmungsaktiv, angenehm und im Alltag leicht'
 ' zu reinigen</p></li>'
 '<li><p>✔ Die stapelbaren Hocker lassen sich platzsparend verstauen und bieten bei Zusammenkünften schnell'
 ' zusätzliche Sitzplätze</p></li>'
 '<li><p>✔ Stahlbeine und ein robuster Sperrholzrahmen tragen bei jedem Sitzhocker bis zu 120 kg</p></li>'
 '<li><p>✔ Die Kunststoff-Fußpolster der Hocker verhindern Kratzer auf dem Boden und reduzieren'
 ' Geräusche</p></li>'
 '<li><p>✔ Keine Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Dunkelgrün</p></li>'
 '<li><p>✔ Material: Stoff in Leinenoptik (100 % Polyester), Schaumstoff, Sperrholz, Stahl</p></li>'
 '<li><p>✔ Gesamtabmessungen: 45B x 45T x 47,5H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 4 x Hocker</p></li><li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 45 x 45 x 47,5 cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Dunkelgrün</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Polyester/Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 12,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 51 × 50 × 34,5 cm</p></li></ul>'
)

K["e5e8754c"] = (
 '<p>Erwecken Sie Ihr Zuhause mit dieser unwiderstehlich charmanten Kommode zum Leben! Das schicke Design'
 ' des Schubladenschranks in zeitlosen Farben fügt sich nahtlos in Ihr Dekor ein und bietet großzügigen'
 ' Stauraum mit drei großen und zwei kleinen Schubladen. Halten Sie Ihre Kleidung, Bücher und Brettspiele'
 ' ordentlich verstaut, während Sie gleichzeitig den vorhandenen Platz perfekt ausnutzen - eine'
 ' geschmackvolle und stilsichere Kombination aus Ästhetik und Funktion!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 2 kleine und 3 große Schubladen bieten Platz für Kleidung, Schlüssel, Magazine und andere Dinge'
 ' des täglichen Bedarfs</p></li>'
 '<li><p>✔ Gefertigt aus MDF-Gehäuse und Kiefernholzfüßen für Stabilität und Robustheit</p></li>'
 '<li><p>✔ Kippschutz der Kommode sorgt für zusätzliche Standfestigkeit</p></li>'
 '<li><p>✔ Vielseitig einsetzbar als Sideboard, Bücherregal, Kommode und mehr</p></li>'
 '<li><p>✔ Neutrale Farben des Aufbewahrungsschranks verleihen einen zeitlosen und chicen Touch</p></li>'
 '<li><p>✔ Ideal für Wohnzimmer, Schlafzimmer, Flur u. v. m.</p></li>'
 '<li><p>✔ Lackierung der unteren Schubladen bewahrt die natürliche Holzmaserung</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß+Dunkelbraun</p></li>'
 '<li><p>✔ Material: MDF, Kiefernholz</p></li>'
 '<li><p>✔ Gesamtmaße: 38T x 70B x 85H cm</p></li>'
 '<li><p>✔ Innenmaße (kleine Schublade): 28,7T x 24,7B x 10H cm</p></li>'
 '<li><p>✔ Innenmaße (große Schublade): 28,7T x 54,9B x 10H cm</p></li>'
 '<li><p>✔ Bodenabstand: 8 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 20 kg (obere Ablagefläche), 5 kg (Schublade)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Kommode</p></li><li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 70L x 38B x 85H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff/Tannenholz</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 28,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 98 × 45,5 × 20,5 cm</p></li></ul>'
)

K["329beada"] = (
 '<p>Dieser schicke Roller von beschleunigt auf bis zu 3 km/h, was sicher für Kinder und angenehm für'
 ' Eltern ist. Per Knopfdruck können Musik- und Lichteffekte eingeschaltet werden. Der bequeme Sitz und'
 ' die stabile Dreirad-Konstruktion bieten einen besonders komfortablen und sicheren Fahrspaß. WARNHINWEIS:'
 ' Das Fahren im Straßenverkehr ist verboten! Benutzung nur unter Beaufsichtigung von Erwachsenen! Achten'
 ' Sie auf entsprechende Schutzausrüstung und einen verantwortungsvollen Umgang!</p>'
 '<h3>Beschreibung:</h3><ul><li><p>✔Elektroroller im realitätsnahen Design</p></li>'
 '<li><p>✔Für Kinder im Alter von 3-5 Jahren geeignet</p></li>'
 '<li><p>✔Ausgestattet mit Lichteffekten und einer Musik-Funktion</p></li>'
 '<li><p>✔Sitzfläche ist weich gepolstert, idealer Sitzkomfort</p></li>'
 '<li><p>✔3 Räder bieten hohe Stabilität</p></li>'
 '<li><p>✔1 x 6 Volt Motor und 1 Akku</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔Material: PP, Metall</p></li>'
 '<li><p>✔Farbe: Rosa+Gelb</p></li><li><p>✔Gesamtmaße: L108 x B51 x H75cm</p></li>'
 '<li><p>✔Sitzmaße: L18 x B23cm</p></li><li><p>✔Akku: 6V, 4AH</p></li>'
 '<li><p>✔Ladezeit: 8-12 h</p></li><li><p>✔Laufzeit mit vollem Akku: ca. 45 min</p></li>'
 '<li><p>✔Geschwindigkeit: 3 km/h</p></li><li><p>✔Gewicht: ca.8,8 kg</p></li>'
 '<li><p>✔Max. Belastbarkeit: ca. 25 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔1 x Elektroroller</p></li>'
 '<li><p>✔1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> L108 x B51 x H75cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Kindermotorrad, Rosa, Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Polypropylen/Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 11,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 86 × 39 × 44,5 cm</p></li></ul>'
)

K["0000fa76"] = (
 '<p>Ihre Katzen werden dieses fantastische Katzenhaus von mit Sicherheit lieben! Das Dach lässt sich leicht'
 ' öffnen, für eine leichte Reinigung und eine gute Durchlüftung. Das massive Tannenholz und der wasserfeste'
 ' Anstrich, sowie das asphaltierte Dach machen das Katzenhaus ideal für Innen- und Außenbereiche. Stylisch'
 ' und funktional wird dieses Haus der neue Lieblingsort Ihrer Katzen.</p>'
 '<h3>Beschreibung:</h3><ul><li><p>✔ 100 % Tannenholz mit umweltfreundlichem Anstrich</p></li>'
 '<li><p>✔ Das Tannenholz ist stabil und langlebig</p></li>'
 '<li><p>✔ 2 Etagen bietet einen großen Raum für Ihre Katze</p></li>'
 '<li><p>✔ Asphalttraufe und wasserfester Anstrich machen das Haus auch in Außenbereichen zum Hit</p></li>'
 '<li><p>✔ Angehobener Boden, um Feuchtigkeitsansammlungen zu verhindern</p></li>'
 '<li><p>✔ Ideal für Drinnen und Draußen</p></li>'
 '<li><p>✔ Fluchttür, Seitentüren, Sprungplattformen und Bodenloch bieten Ihrer Katze viel Spaß beim'
 ' Entdecken</p></li>'
 '<li><p>✔ Das Dach lässt sich leicht öffnen für einfache Reinigung und gute Luftzirkulation</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Material: Tannenholz, Asphaltdach</p></li>'
 '<li><p>✔ Gesamtmaße: L99,5 x B76 x H91 cm</p></li>'
 '<li><p>✔ Maße (Unteretage): L69 x B44 x H33,5 cm</p></li>'
 '<li><p>✔ Maße (Oberetage): L69 x B45 x H44 cm</p></li>'
 '<li><p>✔ Maße (Obere Tür): L17 x H25 cm</p></li>'
 '<li><p>✔ Maße (Fluchttür): L20 x H25,4 cm</p></li>'
 '<li><p>✔ Maße (Seitentür): L17 x H22 cm</p></li>'
 '<li><p>✔ Maße (Sprungplattform): L25 x B20 cm</p></li>'
 '<li><p>✔ Höhe vom Boden: 8,5 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 30 kg</p></li>'
 '<li><p>✔ Farbe: Grau+Weiß</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Katzenhaus</p></li>'
 '<li><p>✔ 1 x Montageanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> L99,5 x B76 x H91 cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Grau, Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Tannenholz</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 17 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 88 × 73 × 16 cm</p></li></ul>'
)

K["8ee517cc"] = (
 '<p>Verwenden Sie diese beiden Hocker von , um Ihrer Küchentheke oder Ihrer Hausbar eine elegante Note zu'
 ' verleihen. Hocker mit einer Oberfläche aus Flanell bietet viel Eleganz. Die geschwungene Rückenlehne und'
 ' das armlose Design unterstützen den Körper und geben ihm Bewegungsfreiheit. Dieser Hocker hat große runde'
 ' Füße aus Metall, die während des Gebrauchs den Hocker aufrecht und stabil halten.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Im 2er-Set verpackt, gibt ihrem Zuhause einen eleganten Look</p></li>'
 '<li><p>✔ Ein Muss für Hausbars, Küchen und hohe Essplätze</p></li>'
 '<li><p>✔ Mit seinem Diamanttufting liegt dieser Barhocker voll im Trend</p></li>'
 '<li><p>✔ Die Sitzhöhe kann auf die Höhe ihrer Theke eingestellt werden</p></li>'
 '<li><p>✔ Der Drehsitz sorgt für eine freie Rotation</p></li>'
 '<li><p>✔ Die untere Fußstütze verhindert, dass die Beine baumeln</p></li>'
 '<li><p>✔ Der Hocker bietet viel Eleganz und ist weich gepolstert</p></li>'
 '<li><p>✔ Der Sockel ist rund, groß und schwer, um den Hocker im Gleichgewicht zu halten</p></li>'
 '<li><p>✔ Rutschfeste Gummipads verhindern Bodenkratzer</p></li>'
 '<li><p>✔ Einfache und schnelle Montage</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Grau</p></li>'
 '<li><p>✔ Material: Schaumstoff, Stahl, samtartiges Polyester</p></li>'
 '<li><p>✔ Gesamtmaße: 54B x 56T x 91-111H cm</p></li>'
 '<li><p>✔ Maße des Sitzes: 46,5B x 41,5T cm</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 2 x Barhocker</p></li><li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 51B x 53T x 92-112H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Grau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Schaumstoff, Stahl, Samtartiges Polyester</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 16,8 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 62 × 62 × 54,5 cm</p></li></ul>'
)

json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)


def summa(s):
    h = 0
    for c in s:
        h = (h * 31 + (ord(c) & 0xFFFF)) % 1000000007
    return h


for k, v in K.items():
    print("%s\t%d\t%d" % (k, summa(v), len(v)))
