#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska källtexterna.

☠️ FILEN ÄR EN AVSKRIFT och får därför inte litas på. Kör
`kontrollera-kalla` (h*31 per produkt, server-side mot skarpa V3)
innan en enda grind körs — samma ordning som N26–N33. Det är SUMMAN
som avgör, inte längden.

☠️ `6b91821a` BÄR LEVERANTÖRENS ARTIKELNUMMER i sin `Technische Daten`
("Artikelnummer: …"). Repot är publikt, så numret är ersatt
med ‹REDIGERAT› här. Kontrollsumman mot Wix räknas därför på texten EFTER
samma ersättning på servern (gatelib.ARTNR-mönstret, speglat i JS) —
annars hade den enda produkt där avskriften medvetet avviker sett ut
som ett transkriberingsfel.
"""
import io, json, collections

K = collections.OrderedDict()

SPEC = '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> '
F = '<li><p><span style="font-weight: 700">'

K["5022e9e5"] = (
 '<p>Verwandeln Sie Ihr Badezimmer mit dem Wäscheschrank in eine stilvolle Oase der Ordnung. Die zwei'
 ' praktischen, nach vorne klappbaren Wäschekörbe ermöglichen ein müheloses Sortieren Ihrer Wäsche und'
 ' sorgen für ein aufgeräumtes Ambiente. Die Lamellentüren des Badezimmerschranks garantieren Frische,'
 ' während der durchdachte Kippschutz für Sicherheit sorgt. Ideal für Haushalte, die praktischen Stil'
 ' schätzen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Zwei vordere Kippbehälter erleichtern das Sortieren und Zugreifen auf die Wäsche</p></li>'
 '<li><p>✔ Bietet Platz für schmutzige Kleidung oder Müll, erhöht die Nutzungsvielfalt</p></li>'
 '<li><p>✔ Lamellentüren sorgen für Belüftung und halten den Inhalt frisch</p></li>'
 '<li><p>✔ Rahmen aus lackiertem MDF gewährleistet Langlebigkeit und eine elegante Optik</p></li>'
 '<li><p>✔ Kippschutz des Badezimmerschranks erhöht die Sicherheit und verhindert Unfälle</p></li>'
 '<li><p>✔ Rutschfeste Füße des Toilettenschranks verhindern Bewegungen und schützen Böden vor'
 ' Kratzern</p></li>'
 '<li><p>✔ Zwei Griffe für einfaches Öffnen und Schließen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: MDF</p></li>'
 '<li><p>✔ Gesamtabmessungen: 70L x 38B x 73H cm</p></li>'
 '<li><p>✔ Wäschekorb Innengröße: 29L x 30B x 44H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 30 kg (gesamt), 10 kg (Wäschekorb), 10 kg (Oberseite)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Wäscheschrank</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '70L x 38B x 73H cm</p></li>'
 + F + 'Färg:</span> Weiß</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 27 kg</p></li>'
 + F + 'Paketmått:</span> 83 × 46 × 25 cm</p></li></ul>'
)

K["32140f01"] = (
 '<p>Nicht nur Ihr Fernseher kann mit Ambilights tolle Atmosphäre schaffen. Unser Wandkamin ist mit'
 ' schönen LEDs ein echter Konkurrent! Diese können Sie ganz bequem per Fernbedienung in verschiedenen'
 ' Farben zuschalten. Die Feueranimation ist hinter der eleganten Glasfront untergebracht. Das lodernde'
 ' Feuer erhellt somit den ganzen Raum und verleiht ihm ein romantisches Flair. So wird gemütliches'
 ' Zurücklehnen ein echtes Erlebnis.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔Moderne und schöne Optik</p></li>'
 '<li><p>✔LED Flamme lässt sich unabhängig von der Hitze ein/ausschalten, 2-stufig dimmbar</p></li>'
 '<li><p>✔2 Heizstufen wählbar, 900/1800W</p></li>'
 '<li><p>✔Mit insgesamt 18 LEDs als Hintergrundbeleuchtung, 7 Farben veränderbar</p></li>'
 '<li><p>✔Thermo-Abschaltung zum Schutz vor Überhitzen</p></li>'
 '<li><p>✔Ein-/Ausschalter an der Oberseite</p></li>'
 '<li><p>✔Mit Kies</p></li>'
 '<li><p>✔Wandmontage</p></li>'
 '<li><p>✔LVD, EMC, GS, ERP geprüft</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔Material: Metall und Sicherheitsglas</p></li>'
 '<li><p>✔Maße: 65 x 11,4 x 52cm (L x B X H)</p></li>'
 '<li><p>✔Farbe: schwarz</p></li>'
 '<li><p>✔Leistung: 900-1800W</p></li>'
 '<li><p>✔Spannung: 220 - 240 V</p></li>'
 '<li><p>✔Kabellänge: 1,6 m</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔1 x Elektrokamin</p></li>'
 '<li><p>✔Inkl. Fernbedienung (2 x AA Batterie nicht enthalten)</p></li>'
 '<li><p>✔Bedienungsanleitung</p></li></ul>'
 + SPEC + 'Modell7/65 x 11,5 x 52cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall und Sicherheitsglas</p></li>'
 + F + 'Vikt:</span> 13 kg</p></li>'
 + F + 'Paketmått:</span> 77 × 20 × 58,5 cm</p></li></ul>'
)

K["4f9ef409"] = (
 '<p>Werten Sie Ihr Wohnzimmer mit diesem weißen TV-Schrank von auf. Das moderne und elegante Design'
 ' dieses Lowboards passt zu jedem Einrichtungsstil. Geeignet für Fernseher bis 60 Zoll, verfügt dieses'
 ' TV-Board über einen geschlossenen Schrank und ein offenes Fach für schnellen Zugriff. Ideal, um'
 ' elektronische Geräte und Kabel praktisch und ordentlich zu verstauen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dieses kompakte TV-Lowboard als TV-Schrank ist für Fernseher bis zu 60 Zoll geeignet</p></li>'
 '<li><p>✔ Das komplett weiße Design verleiht diesem Lowboard jedem Raum Eleganz und Modernität</p></li>'
 '<li><p>✔ Türen mit Griffen und abgeschrägten Kanten unterstreichen den zeitgemäßen Stil dieses'
 ' TV-Boards</p></li>'
 '<li><p>✔ Mit einem Schrank mit Doppeltür und einem offenen Fach für reichlich Stauraum</p></li>'
 '<li><p>✔ Soft-Close-Scharniere sorgen für ein sanftes und geräuschloses Schließen</p></li>'
 '<li><p>✔ Hergestellt aus langlebiger Spanplatte mit einer pflegeleichten Melaminoberfläche</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: Spanplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 140B x 40T x 48H cm</p></li>'
 '<li><p>✔ Schrankinnenraum: 79,8B x 36,5T x 30H cm</p></li>'
 '<li><p>✔ Abmessungen des offenen Regals: 56B x 40T x 36,5H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 45 kg (gesamt), 25 kg (Oberseite), 10 kg (Regalboden)</p></li>'
 '<li><p>✔ Bodenfreiheit: 8 cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x TV-Ständer</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '140 x 40 x 48 cm</p></li>'
 + F + 'Färg:</span> Weiß</p></li>'
 + F + 'Material:</span> Technisches Holz/Melamin</p></li>'
 + F + 'Vikt:</span> 26 kg</p></li>'
 + F + 'Paketmått:</span> 151 × 46,5 × 12,5 cm</p></li></ul>'
)

K["bd2c7da3"] = (
 '<p>Erleben Sie ein aufgeräumtes Heim, in dem jedes Schuhpaar seinen eigenen Platz findet. Der'
 ' Schuhschrank mit sechs anpassbaren Regalen eignet sich ideal für verschiedene Schuh-Arten, von'
 ' Sneakern bis hin zu Stiefeln. Dank leiser Stahldämpfungsscharniere genießen Sie mehr Ruhe und das'
 ' kippsichere Design der Schuhaufbewahrung garantiert Sicherheit in Haushalten mit Kindern.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Das siebenstufige Design des Schuhschranks bietet Platz für bis zu 21 Paar Schuhe.'
 ' Ablagefläche für Schlüssel oder Dekoration inbegriffen</p></li>'
 '<li><p>✔ Verstellbare Regale passen für flache Schuhe oder hohe Stiefel, bis zu EU-Größe 45</p></li>'
 '<li><p>✔ Metall-Scharniere mit sanftem Schließmechanismus garantieren jedes Mal eine leise und sanfte'
 ' Türbewegung</p></li>'
 '<li><p>✔ Hergestellt aus melaminbeschichteter Spanplatte, stabil und leicht zu reinigen</p></li>'
 '<li><p>✔ Kippschutz-Set und rutschfeste Fußpolster des Schuhregals sorgen für Sicherheit</p></li>'
 '<li><p>✔ Moderne, natürliche Oberfläche mit Aluminiumgriffen passt zu jeder Raumdekoration</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: Spanplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 70B x 35T x 108H cm</p></li>'
 '<li><p>✔ Schuhfachabmessungen: 67B x 31,5T x 12,8H cm</p></li>'
 '<li><p>✔ Einstellbare Regalpositionen: 16 Ebenen, 4,5 cm pro Ebene</p></li>'
 '<li><p>✔ Maximale Schuhgröße: EU 45</p></li>'
 '<li><p>✔ Max Belastung: 10 kg (oberes Regal), 3 kg (jedes Regal), 31 kg (gesamt)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Schuhschrank</p></li>'
 '<li><p>✔ 1 x Gebrauchsanleitung</p></li></ul>'
 + SPEC + '70B x 35T x 108H cm</p></li>'
 + F + 'Färg:</span> Weiß</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 33,5 kg</p></li>'
 + F + 'Paketmått:</span> 118 × 47 × 16,5 cm</p></li></ul>'
)

K["6b91821a"] = (
 '<p>Überladene Schubladen und schlechtes Licht lassen den Morgen hektisch wirken. Der Schminktisch'
 ' schafft stilvoll Ordnung im Schlafzimmer. Der LED-Spiegel des Kosmetiktischs mit drei Lichtmodi setzt'
 ' jedes Detail ins rechte Licht; hinter dem Spiegel befinden sich verborgene Ablagen und acht'
 ' Kettenhaken. Sechs offene Fächer und zwei sanft laufende Schubladen ordnen Kosmetik übersichtlich für'
 ' eine entspannte, geordnete Routine.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Der smarte LED-Spiegel bietet drei klare Beleuchtungsmodi von kühlen bis hin zu sanft warmen'
 ' Tönen</p></li>'
 '<li><p>✔ Der Schminktisch bietet mehrstufigen Stauraum mit Ablagen, Schubladen und einem unteren'
 ' Regal</p></li>'
 '<li><p>✔ Versteckter Stauraum hinter dem Spiegel mit zwei Fächern und acht Haken hält wichtige'
 ' Utensilien ordentlich</p></li>'
 '<li><p>✔ Das kompakte Design mit 90B x 40T x 144,7H cm eignet sich ideal für Schlafzimmer und kleine'
 ' Räume</p></li>'
 '<li><p>✔ Die lackierte Oberfläche des Make-up-Tischs lässt sich von verschüttetem Make-up leicht'
 ' sauber wischen</p></li>'
 '<li><p>✔ Kippschutz-Beschläge helfen, den Schminktisch sicher an seinem Platz zu halten</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: MDF</p></li>'
 '<li><p>✔ Gesamtabmessungen: 90L x 40B x 144,7H cm</p></li>'
 '<li><p>✔ Spiegelgröße: 52,8L x 39,5B cm</p></li>'
 '<li><p>✔ Tischplattengröße: 90L x 26B cm</p></li>'
 '<li><p>✔ Größe des oberen offenen Regalfachs: 86,8L x 12,4B x 5H cm</p></li>'
 '<li><p>✔ Größe des Seitenfachs: 22L x 12B x 12H cm, 22L x 12B x 24H cm</p></li>'
 '<li><p>✔ Größe des offenen Regalfachs unter dem Spiegel: 39L x 12B x 11H cm</p></li>'
 '<li><p>✔ Größe des geschlossenen Fachs: 40L x 10B x 17H cm, 40L x 10B x 32H cm</p></li>'
 '<li><p>✔ Größe des unteren Ablagefachs: 86,8L x 15B x 18H cm</p></li>'
 '<li><p>✔ Beinabmessungen: 87L x 23B x 61H cm</p></li>'
 '<li><p>✔ Maximale Belastung: 40 kg (gesamt), 6 kg (Schublade), 3 kg (Ablage)</p></li>'
 '<li><p>✔ Artikelnummer: ‹REDIGERAT›</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Schminktisch</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '90 x 40 x 144,7 cm</p></li>'
 + F + 'Färg:</span> Weiß</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 38 kg</p></li>'
 + F + 'Paketmått:</span> 104 × 47 × 14,5 cm</p></li></ul>'
)

K["3739257b"] = (
 '<p>Verwandeln Sie mit diesem 2er Set Küchenstühle von Ihr Zuhause und den Essbereich. Die Sitzfläche'
 ' mit dicker Schaumstoffpolsterung ist in ein atmungsaktives, leinenähnliches Gewebe gehüllt und bietet'
 ' höchsten Sitzkomfort. Breite Rücken- und Armlehnen stützen Ihren Körper optimal. Dank des robusten'
 ' Metallrahmens und vier Holzbeine des Essstuhls mit verstellbaren Fußpads ist eine hohe Stabilität'
 ' garantiert. Ideal, um Ihr Esszimmer, Wohnzimmer und Schlafzimmer im Modern-Stil zu verschönern!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dieses Set beinhaltet 2 Essstühle, um Ihr Kombinationsproblem zu lösen</p></li>'
 '<li><p>✔ Moderner Stil, geeignet für Esszimmer, Wohnzimmer, Schlafzimmer und mehr</p></li>'
 '<li><p>✔ Dickes Schaumstoffpolster bietet ein komfortables Sitzgefühl</p></li>'
 '<li><p>✔ Bezug aus leinenähnlichem Stoff, weich und atmungsaktiv</p></li>'
 '<li><p>✔ 4 Beine aus Kautschukholz und ein Metallrahmen machen die Eckstühle stabil und robust</p></li>'
 '<li><p>✔ 4 verstellbare Fußpolster halten den Wannenstuhl auch auf unebenen Böden stabil</p></li>'
 '<li><p>✔ Wannenförmiges Design des Polsterstuhls mit Rücken- und Armlehne lässt Sie sich nach langer'
 ' Sitzdauer entspannt fühlen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Beige+Naturholz</p></li>'
 '<li><p>✔ Material: Stoff mit Leinenoptik(100% Polyester), Metall, Schaumstoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 55B x 56T x 74H cm</p></li>'
 '<li><p>✔ Sitzgröße: 44L x 44B cm</p></li>'
 '<li><p>✔ Sitzkissendicke: 8 cm</p></li>'
 '<li><p>✔ Sitzhöhe: 45 cm</p></li>'
 '<li><p>✔ Rückenlehnenhöhe: (bis zur Sitzfläche) 31 cm</p></li>'
 '<li><p>✔ Beinhöhe: 38 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 150 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 2 x Stühle</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '56L x 55B x 74H cm</p></li>'
 + F + 'Färg:</span> Beige</p></li>'
 + F + 'Material:</span> Polyester/Metall</p></li>'
 + F + 'Vikt:</span> 17 kg</p></li>'
 + F + 'Paketmått:</span> 65 × 58 × 56 cm</p></li></ul>'
)

K["8085d0b6"] = (
 '<p>Ein unordentliches und unsicheres Zuhause? Die Angst vor umfallenden Möbeln und Chaos stört den'
 ' Frieden. Das Bücherregal bringt Ordnung und Sicherheit zurück. Breite Schubladen des Bücherschranks'
 ' verstecken Unordnung, offene Fächer ordnen alles von Büchern bis Fotos. Ausgestattet mit einem'
 ' Kippschutz, sichert das Büroregal zuverlässig und bewahrt die Ruhe und Sicherheit Ihrer Familie.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Der Bücherschrank bietet drei offene Regale und drei Schubladen für vielseitige Anzeige- und'
 ' Lagerungsmöglichkeiten</p></li>'
 '<li><p>✔ Modernes Design des Büroregals fügt sich in Wohnzimmer, Arbeitszimmer, Homeoffice,'
 ' Schlafzimmer und mehr ein</p></li>'
 '<li><p>✔ Breit einsetzbar als Bücherregal, Vitrine, Küchenschrank oder Aktenschrank</p></li>'
 '<li><p>✔ Beinhaltet Anti-Kipp-Sets zur Wandmontage, um die Sicherheit Ihrer Familie zu'
 ' gewährleisten</p></li>'
 '<li><p>✔ Spanplatten-Gestell des Bücherregals trägt bis zu 60 kg</p></li>'
 '<li><p>✔ Melaminoberfläche des Bücherschranks ist wasser- und kratzfest, leicht zu reinigen</p></li>'
 '<li><p>✔ Einfache Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: Spanplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 79B x 39,5T x 180H cm</p></li>'
 '<li><p>✔ Offene Regalgröße: 75B x 18,5T x 29,5H cm</p></li>'
 '<li><p>✔ Schubladeninnenmaß: 69,3B x 28,5T x 18,5H cm</p></li>'
 '<li><p>✔ Maximale Belastung: 5 kg (Regal/Schublade), 10 kg (Arbeitsplatte), 60 kg (Gesamt)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Bücherregal</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '79L x 39,5B x 180H cm</p></li>'
 + F + 'Färg:</span> Weiß</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 42 kg</p></li>'
 + F + 'Paketmått:</span> 104 × 48 × 19 cm</p></li></ul>'
)

K["3bf5bd08"] = (
 '<p>Die beste gemeinsame Zeit verbringt man in einer warmen und einladenden Umgebung. Dieses'
 ' Esstisch-Set von bietet genau das: Platz für vier Personen mit einem rechteckigen Tisch und vier'
 ' Stühlen und universelle Einsatzmöglichkeiten dank der kompakten Größe. Genießen Sie einen spannenden'
 ' Spieleabend oder ein gemütliches Abendessen mit Familie und Freunden.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Moderne Interpretation der Allzweck-Sitzgruppe</p></li>'
 '<li><p>✔ Kompaktes Design, ideal für kleinere Räume</p></li>'
 '<li><p>✔ 5-teiliges Set: 1 Tisch und 4 passende Stühle</p></li>'
 '<li><p>✔ Hergestellt aus MDF und stabilem Stahlrahmen für eine lange Lebensdauer</p></li>'
 '<li><p>✔ Extrem pflegeleichte Oberflächen</p></li>'
 '<li><p>✔ Einfache Montage</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Material: MDF, Metall</p></li>'
 '<li><p>✔ Farbe: Naturholzmaserung + Weiß</p></li>'
 '<li><p>✔ Maße Tisch: L100 x B63 x H76,5 cm</p></li>'
 '<li><p>✔ Maße Stuhl: L40 x B45 x H82 cm</p></li>'
 '<li><p>✔ Sitzfläche: 36L x 39B cm</p></li>'
 '<li><p>✔ Sitzhöhe 47,5 cm</p></li>'
 '<li><p>✔ max. Belastbarkeit: 80 kg (Tisch), 100 kg (pro Stuhl)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Tisch</p></li>'
 '<li><p>✔ 4 x Stuhl</p></li>'
 '<li><p>✔ 1 x Montageanleitung</p></li></ul>'
 + SPEC + '100L x 63B x 76,5H cm</p></li>'
 + F + 'Färg:</span> Hellgrau</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 30,7 kg</p></li>'
 + F + 'Paketmått:</span> 116 × 73 × 18 cm</p></li></ul>'
)

if __name__ == "__main__":
    json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    for kort, html in K.items():
        print(f"{kort}\t{len(html)} tecken")
