#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska kalltexterna.

☠️ FILEN AR EN AVSKRIFT och far darfor inte litas pa. Kor
`kontrollera-kalla` (h*31 per produkt, server-side mot skarpa V3)
innan en enda grind korts — samma ordning som N26, N27 och N28. N27:s
forsta korning gav 7 av 8 och fallde ett akta transkriberingsfel med
RATT teckenantal men fel summa.
"""
import io, json, collections

K = collections.OrderedDict()

K["ad46f9cc"] = (
 '<p>Erkunden Sie die Gegend mit dem Motorrad für Kinder, ausgestattet mit manueller Drosselklappe für'
 ' Geschwindigkeiten zwischen 2,4 und 5 km/h. Perfekt für kleine Biker, inklusive Stützrädern für'
 ' konstanten Fahrspaß. Genießen Sie eingebaute Musik und eine sanfte Fahrt auf unterschiedlichen'
 ' Untergründen dank der stoßabsorbierenden Hinterräder des Elektromotorrads. Ein spannendes'
 ' Kinderfahrzeug für junge Entdecker!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Der realistische Drehgasgriff sorgt für eine sanfte Geschwindigkeitskontrolle und ein'
 ' mitreißendes Fahrgefühl</p></li>'
 '<li><p>✔ Zwei Motoren liefern gleichmäßige Leistung für sicheres und souveränes Fahren</p></li>'
 '<li><p>✔ Die Hinterradfederung des Elektromotorrads reduziert Unebenheiten für eine ruhigere,'
 ' komfortablere Fahrt</p></li>'
 '<li><p>✔ Tiefprofilierte Räder verbessern den Grip auf verschiedenen ebenen Straßenoberflächen</p></li>'
 '<li><p>✔ Abnehmbare Stützräder des Kindermotorrads unterstützen Anfänger und fördern das wachsende'
 ' Fahrvertrauen</p></li>'
 '<li><p>✔ Lange Akkulaufzeit ermöglicht ausgedehnten Spielspaß im Freien ohne Unterbrechungen</p></li>'
 '<li><p>✔ Ergonomischer Sitz und Musikfunktionen erhöhen Komfort und Fahrvergnügen</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Blau</p></li>'
 '<li><p>✔ Material: Kunststoff, Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 109,5L x 60B x 72,5H cm</p></li>'
 '<li><p>✔ Geschwindigkeit: 2,4-5 km/h</p></li>'
 '<li><p>✔ Sitzgröße: 15L x 36B x 53H cm (vom Boden)</p></li>'
 '<li><p>✔ Raddurchmesser: Ø34 cm</p></li>'
 '<li><p>✔ Ladezeit: 8-10 Stunden (erstes Mal), 10-12 Stunden (regulär)</p></li>'
 '<li><p>✔ Laufzeit: 30–45 Minuten</p></li>'
 '<li><p>✔ Batterie: 12V 4,5AH</p></li>'
 '<li><p>✔ Motor: 2 x 12V</p></li>'
 '<li><p>✔ Belastbarkeit: 30 kg</p></li>'
 '<li><p>✔ Qualifiziertes Alter: 3-8 Jahre</p></li>'
 '<li><p>✔ Empfohlenes Alter: 3-6 Jahre</p></li>'
 '<li><p>✔ Hinweis: Überwachen Sie Ihre Kinder stets, während sie fahren</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Elektrisches Aufsitz-Motorrad</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 109,5L x 60B x 72,5H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Blau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Kunststoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 13,1 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 72 × 50 × 40 cm</p></li></ul>'
)

K["93b9d4da"] = (
 '<p>Mit den hübschen Aufbewahrungsboxen von wird das Ordnunghalten zum Vergnügen! Das kindgerechte'
 ' Design mit abgerundeten Kanten sorgt für Sicherheit und Spaß zugleich. Neun geräumige Schubladen'
 ' bieten viel Platz für Spielzeug, Kleidung, Kissen und andere Dinge. So wird das Aufräumen zum'
 ' Kinderspiel. Bringen Sie Freude und Ordnung ins Kinderzimmer – mit den praktischen'
 ' Aufbewahrungsboxen von !</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Neun große Schubladen und eine breite Fläche bieten großzügigen Stauraum für Spielzeug,'
 ' Kleidung, Puppen, Kissen und mehr</p></li>'
 '<li><p>✔ Runde Polierkante verhindert, dass sich Ihr Kind verletzt</p></li>'
 '<li><p>✔ Blaue Farbtöne machen die Aufbewahrungsboxen zu einer tollen Dekoration für das'
 ' Kinderzimmer</p></li>'
 '<li><p>✔ Das erhöhte Design schützt vor Feuchtigkeit von unten</p></li>'
 '<li><p>✔ Ideal für Schlafzimmer, Kinderzimmer, Kindergarten oder Wohnzimmer – überall, wo'
 ' zusätzlicher Platz benötigt wird</p></li>'
 '<li><p>✔ Einfaches und kindgerechtes Design zum Herausziehen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Blau</p></li>'
 '<li><p>✔ Material: Kunststoff</p></li>'
 '<li><p>✔ Gesamtmaße: 113L x 37B x 56,5H cm</p></li>'
 '<li><p>✔ Schubladengröße (Innenraum): 31L x 29,5B x 15H cm</p></li>'
 '<li><p>✔ Höhe der Füße: 2,5 cm</p></li>'
 '<li><p>✔ Belastbarkeit (jede Ebene): 10 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Aufbewahrungsbox</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 113L x 37B x 56,5H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Blau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Kunststoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 14,1 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 75 × 40 × 51 cm</p></li></ul>'
)

K["681e5c63"] = (
 '<p>Mit dem Fahrrad lässt sich sehr wohl viel transportieren. Mit dem Lastenanhänger von sogar sehr'
 ' einfach. Die Universal-Anhängerkupplung passt an fast jedes Fahrrad und ist schnell an- und wieder'
 ' abmontiert. Der robuste Stahlrahmen lässt eine Beladung von bis zu 40 kg zu. Mit den 20-Zoll-Reifen'
 ' ist sich der Anhänger auch vollbeladen noch leicht zu ziehen und die Felgenreflektoren sorgen für'
 ' eine bessere Sichtbarkeit.</p>'
 '<h3>Beschreibung:</h3><ul><li><p>✔Sehr stabiler, pulverbeschichteter Stahlrohrrahmen mit'
 ' Überrollbügel</p></li>'
 '<li><p>✔Strapazierfähiger, pflegeleichter Bezug</p></li>'
 '<li><p>✔20" Luftbereifung mit Schnellverschlüssen</p></li>'
 '<li><p>✔Räder leicht demontierbar zum platzsparenden Verstauen</p></li>'
 '<li><p>✔Abnehmbares Verdeck</p></li>'
 '<li><p>✔Inklusive Anhängerkupplung</p></li>'
 '<li><p>✔StVO-zugelassen bei Nachrüstung eines zugelassenen Rücklichtes</p></li>'
 '<li><p>✔Einfache und schnelle Montage und Demontage ohne Werkzeug</p></li>'
 '<li><p>✔Zwei Reflektoren pro Rad</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔Material: Stahl und Oxford</p></li>'
 '<li><p>✔Gesamtmaße: L140 x B77 x H65 cm</p></li>'
 '<li><p>✔Transportbox: L86x B57 x H36 cm</p></li>'
 '<li><p>✔Luftbereifung: 20 Zoll</p></li>'
 '<li><p>✔Farbe: Weiß/Schwarz</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔1 x Transportanhänger</p></li>'
 '<li><p>✔1 x Artikelanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> M</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß, Schwarz</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Stahl, Oxford</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 16 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 91 × 20 × 66 cm</p></li></ul>'
)

K["5d2a44cf"] = (
 '<p>Entdecken Sie das Softbaustein-Set – der perfekte Spielplatz für Ihre Kleinen! Mit bunten,'
 ' verschieden geformten Schaumstoffbausteine fördert es die Fantasie und Kreativität Ihrer Kinder.'
 ' Die weichen Schaumstoffbausteine bieten eine sichere Umgebung zum Laufen, Springen und Krabbeln.'
 ' Dank der einfachen Reinigung mit Desinfektionstüchern bleibt alles hygienisch. Schenken Sie Ihren'
 ' Kindern endlosen Spaß und eine sichere Spielumgebung!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Sieben Schaumstoffbausteine, die Spaß bieten und Kreativität fördern</p></li>'
 '<li><p>✔ Weiches Softbaustein Set mit einem Quadrat, Treppen, einer Rampe, Sektor- und'
 ' Schrägstücken</p></li>'
 '<li><p>✔ Leicht zu reinigen – einfach mit einem Desinfektionstuch abwischen</p></li>'
 '<li><p>✔ Empfohlenes Alter: 12-36 Monate</p></li>'
 '<li><p>✔ Zertifiziertes Alter: 12-36 Monate</p></li>'
 '<li><p>✔ Maximale Belastung der Softbausteine 60 kg, keine Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Mehrfarbig</p></li>'
 '<li><p>✔ Material: Kunstleder, EPE</p></li>'
 '<li><p>✔ Maße: 170L x 130B x 40H cm</p></li>'
 '<li><p>✔ Blauer quadratischer Block: 55L x 40B x 38H cm</p></li>'
 '<li><p>✔ Lila: 40L x 27,5B x 27,5H cm</p></li>'
 '<li><p>✔ Dunkelblau: 45L x 30B x 15H cm</p></li>'
 '<li><p>✔ Halb-zylindrischer Block: 40L x 30B x 27,5H cm</p></li>'
 '<li><p>✔ Ovaler Block: 55L x 40B x 3H cm</p></li>'
 '<li><p>✔ Trapezförmiger Block: 55L x 40B x 25H cm</p></li>'
 '<li><p>✔ Empfohlenes Alter: 12-36 Monate</p></li>'
 '<li><p>✔ Zertifiziertes Alter: 12-36 Monate</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Softplay-Set für Kinder</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 170cm x 130cm x 40cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Mehrfarbig</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Kunstleder, EPE</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 7,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 90 × 42 × 57 cm</p></li></ul>'
)

K["16a26891"] = (
 '<p>Vermissen Ihre Kinder den Spielplatzspaß? Die Kinderschaukel ermöglicht mehr Outdoor-Zeit und'
 ' fördert spielerisch die motorische Entwicklung. Mit verstellbaren Seilen passen Sie die'
 ' Schaukelsitze individuell an, um optimalen Komfort und Freude zu gewährleisten. Diese'
 ' Kinderschaukel für draußen beinhaltet zwei Sitze und eine Gleitvorrichtung und bietet Platz für'
 ' drei Kinder, die gemeinsam Spaß haben können.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 2 Kinderschaukelsitze und 1 Gleiterset für vier Kinder zum gemeinsamen Spielen</p></li>'
 '<li><p>✔ Fördert das Gleichgewicht und die Koordination der Kinder</p></li>'
 '<li><p>✔ Verstellbare Länge passt sich der Größe Ihres Kindes im Laufe seines Lebens an</p></li>'
 '<li><p>✔ Metallrahmen der Kinderschaukel mit A-Rahmen-Design, ausgelegt auf Balance</p></li>'
 '<li><p>✔ Empfohlen für Kinder über 3 Jahre</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Grün+Blau</p></li>'
 '<li><p>✔ Material: Metall, Kunststoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 280L x 140B x 178H cm</p></li>'
 '<li><p>✔ Schaukelsitz: 35L x 17,3B cm</p></li>'
 '<li><p>✔ Gleiter: 101L x 20B cm</p></li>'
 '<li><p>✔ Belastbarkeit: 90 kg (Wippe), 45 kg (je Schaukelsitz), 180 kg (gesamt)</p></li>'
 '<li><p>✔ Empfohlenes Alter: 3+ Jahre</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 2 x Schaukelsitze</p></li>'
 '<li><p>✔ 1 x Wippe</p></li>'
 '<li><p>✔ 4 x Bodenanker</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 280L x 140B x 178H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Grün</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Metall</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 20,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 123 × 35 × 15,8 cm</p></li></ul>'
)

K["c9c98333"] = (
 '<p>Teilen Sie die Campingfreude mit Familie und Freunden. Das Drei-Raum-Tunnelzelt für 4 Personen'
 ' bietet zwei Schlafzimmer, Wohnbereich, robuste Fiberglasstangen, 2.000 mm Regenschutz, Türen,'
 ' Mesh-Fenster, 28 Anker, 10 Seile und Tragetasche.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Zwei Schlafzimmer und ein Wohnbereich. Für vier Personen</p></li>'
 '<li><p>✔ Laternenhaken für Beleuchtung in der Nacht – hält offene Flammen fern</p></li>'
 '<li><p>✔ Zwei Türen für einfachen Zugang</p></li>'
 '<li><p>✔ Wasserdicht bis zu 2.000 mm Regenwasser</p></li>'
 '<li><p>✔ 28 Bodenanker, 10 Abspannseile und Tragetasche inklusive</p></li>'
 '<li><p>✔ Hinweis: Bitte beachten Sie, dass dieses Zelt nicht für Übernachtungen bei Regenwetter'
 ' empfohlen wird</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Grau+Blau</p></li>'
 '<li><p>✔ Materialien: 190T Polyester-Taft, Fiberglas</p></li>'
 '<li><p>✔ Gesamtmaße: 555L x 225B x 190H cm</p></li>'
 '<li><p>✔ Gefaltete Maße: 74L x 26B x 26H cm</p></li>'
 '<li><p>✔ Schlafzimmermaße: 208L x 170B x 152H cm</p></li>'
 '<li><p>✔ Türmaße: 91B x 158H cm</p></li>'
 '<li><p>✔ Gewichtskapazität: 1 kg (oberer Haken)</p></li>'
 '<li><p>✔ Nettogewicht: 8,5 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Campingzelt</p></li>'
 '<li><p>✔ 28 x Bodenanker</p></li>'
 '<li><p>✔ 10 x Abspannseil</p></li>'
 '<li><p>✔ 1 x Tragetasche</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 555L x 225B x 190H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Blau</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Polyester/Glasfaser</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 9,5 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 72 × 27 × 22 cm</p></li></ul>'
)

K["346b40f7"] = (
 '<p>Nach langen Sitz- oder Arbeitsstunden verdient Ihr Körper echte Erholung. Der Inversionstisch'
 ' dekomprimiert sanft Ihre Wirbelsäule und lindert tägliche Rückenspannung, um Komfort in Ihren'
 ' Alltag zu bringen. Dank der sanften Inversionsbewegung. Der platzsparende Klapprahmen der'
 ' Inversionstabelle passt perfekt in Ihr Zuhause – für Dehnen, Entspannen und Auftanken zu jeder'
 ' Zeit.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Diese Inversionsbank hilft, Rückenspannungen durch sanfte Wirbelsäuleninversion zu'
 ' lindern</p></li>'
 '<li><p>✔ Inversionsbereich von 0-90° für eine gleichmäßige Bewegung</p></li>'
 '<li><p>✔ Dreieckiger Stahlrahmen mit Sicherheitsgurt für eine sichere Nutzung der'
 ' Inversionstabelle</p></li>'
 '<li><p>✔ Geeignet für Benutzer von 140-196 cm mit 21-stufiger Rückenlehnenverstellung</p></li>'
 '<li><p>✔ 7-stufige Knöchelarretierung sorgt für einen festen und sicheren Sitz</p></li>'
 '<li><p>✔ Gepolsterte Rückenlehne und Armlehnen bieten zusätzlichen Komfort und'
 ' Unterstützung</p></li>'
 '<li><p>✔ Klappbares Design spart Platz und ermöglicht eine einfache Aufbewahrung zu Hause</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz+Rot</p></li>'
 '<li><p>✔ Material: Stahl</p></li>'
 '<li><p>✔ Gesamtabmessungen: 122L x 59B x 130H cm</p></li>'
 '<li><p>✔ Gefaltete Größe: 71L x 63B x 168H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 120 kg</p></li>'
 '<li><p>✔ Hinweis: Konsultieren Sie einen Arzt, bevor Sie das Produkt verwenden, wenn Sie an'
 ' Bluthochdruck, Herzproblemen oder anderen medizinischen Beschwerden leiden</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Inversionstisch</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 122L x 59B x 130H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Schwarz+Rot</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Stahl</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 19 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 117 × 66,5 × 11,5 cm</p></li></ul>'
)

K["b373ce2d"] = (
 '<p>Ein überfülltes Wohnzimmer erschwert die Entspannung. Das TV Schrank sorgt für ein ruhiges,'
 ' offenes Ambiente, indem es Platz schafft und alles ordentlich verstaut. Drei Klappschränke bieten'
 ' Platz für Fernbedienungen und Konsolen, die 180 cm lange Oberfläche passt für Fernseher bis zu'
 ' 82". Soft-Close-Scharniere und weiße Türen des TV Lowboards verleihen elegante Ruhe und moderne'
 ' Frische für den Alltag.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Das wandmontierte Design des Fernsehschranks schafft Freiraum auf dem Boden für einen'
 ' sauberen, offenen Wohnbereich</p></li>'
 '<li><p>✔ Drei herunterklappbare Schränke halten Fernbedienungen, Konsolen und Filme ordentlich'
 ' versteckt</p></li>'
 '<li><p>✔ Die 180 cm breite Oberfläche eignet sich für Fernseher bis zu 82 Zoll, um die perfekte'
 ' Unterhaltungsecke zu schaffen</p></li>'
 '<li><p>✔ Soft-Close-Scharniere sorgen für leises und sanftes Schließen für ein friedliches'
 ' Zuhause</p></li>'
 '<li><p>✔ Die leicht zu reinigende Melaminoberfläche hält Ihren TV-Schrank frisch und'
 ' makellos</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Weiß</p></li>'
 '<li><p>✔ Material: MDF</p></li>'
 '<li><p>✔ Gesamtabmessungen: 180B x 31,5T x 29,8H cm</p></li>'
 '<li><p>✔ Innenmaße des Schranks: 57,3B x 28,3T x 25,3H cm</p></li>'
 '<li><p>✔ Maximale Belastung: 30 kg (gesamt), 15 kg (oben)</p></li>'
 '<li><p>✔ Geeignete Fernsehergröße: Bis zu 82 Zoll</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x schwebendes TV-Board</p></li>'
 '<li><p>✔ 1 x Gebrauchsanleitung</p></li></ul>'
 '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> 180L x 31,5B x 29,8H cm</p></li>'
 '<li><p><span style="font-weight: 700">Färg:</span> Weiß</p></li>'
 '<li><p><span style="font-weight: 700">Material:</span> Holzwerkstoff</p></li>'
 '<li><p><span style="font-weight: 700">Vikt:</span> 27 kg</p></li>'
 '<li><p><span style="font-weight: 700">Paketmått:</span> 103 × 39,5 × 20 cm</p></li></ul>'
)

json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)


def summa(s):
    h = 0
    for c in s:
        h = (h * 31 + (ord(c) & 0xFFFF)) % 1000000007
    return h


for k, v in K.items():
    print("%s\t%d\t%d" % (k, summa(v), len(v)))
