#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska källtexterna (hämtade server-side
via ExecuteWixAPI mot skarpa V3, ?fields=PLAIN_DESCRIPTION).

☠️ FILEN ÄR EN AVSKRIFT och får därför inte litas på. Kör kontrollen mot
skarpa V3 (samma anrop som ingen skrivning) innan en enda grind körs — samma
ordning som N26–N39. Det är SUMMAN som avgör, inte längden.

Ingen av rundans tio källtexter bär ett artikelnummer, så ingen rad är
redigerad och summan räknas på texten precis som den står i Wix.
"""
import io, json, collections

K = collections.OrderedDict()

SPEC = '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> '
F = '<li><p><span style="font-weight: 700">'

K["27ff1a8e"] = (
 '<p>Weihnachtsdeko leicht gemacht, für immer! Dieser Weihnachtsbaum ist ein pflegeleichtes Must-Have für die'
 ' bevorstehende Festzeit. Aus flammhemmendem Kunststoff hergestellt, garantiert der Weihnachtsbaum Sicherheit in'
 ' Ihrem Zuhause. Einfach aufstellen, dank des Fertigdesigns. Mit integrierten LEDs sparen Sie sich die Lichterkette'
 ' und können bei Bedarf zusätzlichen Baumschmuck anbringen. Inklusive Ständer für eine sichere Stabilität.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 50 LED-Leuchten mit 6h-Timer vom Christbaum verbrauchen wenig Energie und sind kühl berührbar</p></li>'
 '<li><p>✔ Dekoriert mit roten Beerentrauben und Tannenzapfen</p></li>'
 '<li><p>✔ Schneebedeckte Enden für einen zusätzlichen winterlichen Look</p></li>'
 '<li><p>✔ 0,6 m hoch Weihnachtsbaum geeignet für Schreibtisch, Boden oder Regal</p></li>'
 '<li><p>✔ Flammhemmende Zweige des Weihnachtsbaums: fangen nicht Feuer. Nicht in die Nähe von offenen Flammen'
 ' stellen zur Sicherheit</p></li>'
 '<li><p>✔ Zementbasis in Leinen gewickelt für einen stabilen Stand</p></li>'
 '<li><p>✔ Nur für die Nutzung in Innenräumen</p></li>'
 '<li><p>✔ Keine Montage erforderlich</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Baumfarbe: Grün+Weiß</p></li>'
 '<li><p>✔ Lichtfarbe: Warmweiß</p></li>'
 '<li><p>✔ Materialien: Kunststoff, Metall, Polyester, Zement</p></li>'
 '<li><p>✔ Gesamtabmessungen: Ø35 x 60H cm. Kabel: 0,3 m</p></li>'
 '<li><p>✔ Sockelgröße: Ø11 x 4H cm</p></li>'
 '<li><p>✔ Spitzenanzahl: 86. Lichtanzahl: 50</p></li>'
 '<li><p>✔ Eingang: 1,5V</p></li>'
 '<li><p>✔ Hinweis: Es dauert ungefähr 5 Minuten, alle einzelnen Spitzen auszubreiten für ein vollständiges'
 ' Aussehen</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Weihnachtsbaum</p></li>'
 '<li><p>✔ 7 x Tannenzapfen</p></li>'
 '<li><p>✔ 7 x Beerenzweige</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '35L x 35B x 60H cm</p></li>'
 + F + 'Färg:</span> Grün+Weiß</p></li>'
 + F + 'Material:</span> Metall, Kunststoff</p></li>'
 + F + 'Vikt:</span> 2,2 kg</p></li>'
 + F + 'Paketmått:</span> 16,5 × 16,5 × 50 cm</p></li></ul>'
)

K["c2c6a332"] = (
 '<p>Unser rechteckiger Wandspiegel bringt Eleganz und Charme in Ihre Räumlichkeiten. Mit seinen großzügigen'
 ' Abmessungen von 40 x 60 cm und dem modernen MDF-Rahmen ist dieser rechteckige Spiegel die perfekte Ergänzung für'
 ' Ihr Wohnzimmer, Schlafzimmer oder den Eingangsbereich. Er reflektiert nicht nur Licht, sondern auch Ihre'
 ' Persönlichkeit und schafft eine einladende Atmosphäre. Setzen Sie Akzente in Ihrer Einrichtung und genießen Sie'
 ' die zeitlose Ästhetik.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dieser Wandspiegel bringt einen dekorativen Akzent in Ihr Zuhause und erhellt Ihr Interieur</p></li>'
 '<li><p>✔ Rahmen und Halterung der Flurspiegel aus MDF für eine langlebige Nutzung</p></li>'
 '<li><p>✔ Zwei Montagemöglichkeiten: Wandmontage oder Aufhängung</p></li>'
 '<li><p>✔ Ausgestattet mit 4 Haken auf der Rückseite für eine einfache Montage an der Wand, sowohl horizontal als'
 ' auch vertikal</p></li>'
 '<li><p>✔ Ideal für Flure, Badezimmer, Wohnzimmer oder Schlafzimmer – eine subtile, elegante und zeitlose'
 ' Ergänzung, die zu jedem Einrichtungsstil passt</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Materialien: MDF, Glas</p></li>'
 '<li><p>✔ Gesamtabmessungen: 40L x 60H cm</p></li>'
 '<li><p>✔ Spiegeltiefe: 20 mm</p></li>'
 '<li><p>✔ Glasstärke: 2 mm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Wandspiegel</p></li>'
 '<li><p>✔ 1 x Schraubenset</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '40 x 60 cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Holzwerkstoff/Glas</p></li>'
 + F + 'Vikt:</span> 2,6 kg</p></li>'
 + F + 'Paketmått:</span> 69 × 49 × 7 cm</p></li></ul>'
)

K["e2cfbd07"] = (
 '<p>Modernisieren Sie Ihre Küche mit dem Mikrowellenregal, einer stilvollen Aufbewahrungslösung, die Ordnung und'
 ' Übersichtlichkeit schafft. Mit einem unteren Freiraum von 40 cm bietet es Platz für die meisten Geräte, während'
 ' drei Haken Ihre Utensilien stets zur Hand halten. Von 39,5 bis 64 cm erweiterbar, verwandelt sich das Regal in'
 ' eine schicke Kaffeestation, die sich perfekt in jedes Ambiente einfügt.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Die Bodenhöhe von 40 cm passt für die meisten Küchengeräte</p></li>'
 '<li><p>✔ Enthält 3 Haken für Utensilien und Ofenhandschuhe</p></li>'
 '<li><p>✔ Die Länge des Küchenregals lässt sich von 39,5 bis 64 cm ausziehen für vielseitigen Einsatz</p></li>'
 '<li><p>✔ Metallkonstruktion garantiert Langlebigkeit und Stabilität</p></li>'
 '<li><p>✔ Verstellbare Fußpolster sorgen für eine ebene Aufstellung auf unebenen Oberflächen</p></li>'
 '<li><p>✔ Einfaches und elegantes Aussehen des Mikrowellenregals passt in Küche, Büro oder Arbeitszimmer</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Materialien: Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 39,5-64B x 32T x 47,5H cm</p></li>'
 '<li><p>✔ Fußhöhe: 40 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 15 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Mikrowellenofenregal</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '39,5-64L x 32B x 47,5H cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 3 kg</p></li>'
 + F + 'Paketmått:</span> 53 × 36 × 10,5 cm</p></li></ul>'
)

K["a7d072fc"] = (
 '<p>Erleben Sie elegante Ordnung mit dem Weinregal. Dieses vierstöckige Gestell fasst bis zu 16 Flaschen.'
 ' Innovative Schnallen des Flaschenständers sorgen für Stabilität und wellenförmige Regale für eine edle Note.'
 ' Ideal für Weinliebhaber, die ihre Kollektion stilvoll präsentieren und lagern möchten!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Die vierstufige Struktur bietet Platz für bis zu 16 Weinflaschen</p></li>'
 '<li><p>✔ Einzelne oder stapelbare Ebenen mit Schnallendesign zur Sicherung</p></li>'
 '<li><p>✔ Wellenförmige Regale des Weinständers sorgen für eine exquisite Optik</p></li>'
 '<li><p>✔ Robustes, pulverbeschichtetes Metall des Weinflaschenhalters gewährleistet Langlebigkeit</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Metall</p></li>'
 '<li><p>✔ Gesamtabmessungen: 42,5B x 16,5T x 41H cm</p></li>'
 '<li><p>✔ Größe pro Ebene: 42,5B x 16,5T x 11H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 32 kg (gesamt)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Weinregal</p></li>'
 '<li><p>✔ 1 x Gebrauchsanleitung</p></li></ul>'
 + SPEC + '42,5L x 16,5B x 41H cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 2,4 kg</p></li>'
 + F + 'Paketmått:</span> 45 × 18 × 12 cm</p></li></ul>'
)

K["4a4721fa"] = (
 '<p>Spielzeit auf einer Baby-Bodenmatte kann rutschig sein. Diese Sorge stört das fantasievolle Spielen. Die'
 ' Baby-Bodenmatte löst das Problem mit einem doppelseitigen rutschfesten Design für Stabilität. Ihre weiche Textur'
 ' und das elegante graue Stadtbild passen perfekt zur Einrichtung und schaffen einen sicheren, stilvollen Ort für'
 ' die Kreativität Ihres Kindes und Ihre Gelassenheit.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Mit einem lustigen Stadtverkehr-Thema gestaltet, um fantasievolles und lehrreiches Spielen'
 ' anzuregen</p></li>'
 '<li><p>✔ Bietet eine großzügige Spielfläche von 1,6 m² für aktives tägliches Spielen</p></li>'
 '<li><p>✔ Doppelte rutschfeste Konstruktion mit sicherer Oberfläche und Rückseite für zusätzliche'
 ' Sicherheit</p></li>'
 '<li><p>✔ Hergestellt aus langlebigem 100 % Polyester, ist diese Baby-Spielmatte weich und bequem</p></li>'
 '<li><p>✔ Farbenfrohes Design fördert Kreativität und frühkindliches Lernen</p></li>'
 '<li><p>✔ Einfach zu reinigen mit einem Staubsauger, bei Bedarf Fleckenreinigung bei Verschmutzungen</p></li>'
 '<li><p>✔ Keine Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Grau</p></li>'
 '<li><p>✔ Material: 100 % Polyester</p></li>'
 '<li><p>✔ Gesamtabmessungen: 160L x 100B x 0,5H cm</p></li>'
 '<li><p>✔ Abdeckfläche: 1,6 m²</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Baby-Spielmatte</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '160L x 100B x 0,5H cm</p></li>'
 + F + 'Färg:</span> Grau</p></li>'
 + F + 'Material:</span> Polyester</p></li>'
 + F + 'Vikt:</span> 2,2 kg</p></li>'
 + F + 'Paketmått:</span> 43 × 31 × 11 cm</p></li></ul>'
)

K["8ded5e38"] = (
 '<p>Sind Sie besorgt darüber, dass zu viel Bildschirmzeit Ihrem Kind nicht guttut? Es ist beunruhigend, wenn beim'
 ' Spielen keine wichtigen Fähigkeiten gefördert werden. Das Schaukelpferd von bietet eine unterhaltsame Lösung. Mit'
 ' der breiten, kippsicheren Basis und der sanften Bewegung des Schaukeltiers stärkt es die Kernmuskulatur und'
 ' Koordination Ihres Kindes, verwandelt Spielspaß in gesundes Aufwachsen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Einzigartiges Löwen-Design mit lebendigen Farben regt die Fantasie an</p></li>'
 '<li><p>✔ Breite Basis und abgerundete Kanten des Baby Schaukelstuhls bieten sicheren Schaukelspaß</p></li>'
 '<li><p>✔ Fördert der Kinderschaukelstuhl die Entwicklung von Kernkraft, Gleichgewicht und Koordination</p></li>'
 '<li><p>✔ Aus stabilem Holz gefertigt, um die Kleinkindjahre zu überdauern</p></li>'
 '<li><p>✔ Stabile Konstruktion des Kinderschaukelstuhls trägt bis zu 25 kg, geeignet für Kinder von 2-5'
 ' Jahren</p></li>'
 '<li><p>✔ Tolles Geschenk, um wertvolle Familienerinnerungen zu schaffen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Orange</p></li>'
 '<li><p>✔ Material: Mehrschichtplatte</p></li>'
 '<li><p>✔ Gesamtabmessungen: 59L x 27B x 44H cm</p></li>'
 '<li><p>✔ Sitzgröße: 15B x 30T cm</p></li>'
 '<li><p>✔ Sitzhöhe: 28,5 cm</p></li>'
 '<li><p>✔ Basisgröße: 59L x 27B cm</p></li>'
 '<li><p>✔ Zugelassenes Alter: 2+ Jahre</p></li>'
 '<li><p>✔ Empfohlenes Alter: 2–5 Jahre</p></li>'
 '<li><p>✔ Belastbarkeit: 25 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Kinder-Schaukelpferd</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '59cm x 27cm x 44cm</p></li>'
 + F + 'Färg:</span> Orange</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 2,9 kg</p></li>'
 + F + 'Paketmått:</span> 50 × 47 × 7,5 cm</p></li></ul>'
)

K["5cdc868a"] = (
 '<p>Ist Ihre Garderobe zu klein, um alle Ihre Kleidungstücke zu verstauen? Ja, mit diesem Garderobenständer wird'
 ' Ihr Problem des mangelnden Speicherplatzes lösen. Wir bieten Ihnen dieses Set mit ausgezeichnetem Preis- und'
 ' Qualitätsverhältnis. Die Schrankleiste lässt sich zudem in Breite und Höhe verstellen und passt sich so perfekt'
 ' Ihren Bedürfnissen an!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔stabiler und belastbarer Kleiderständer</p></li>'
 '<li><p>✔aus Edelstahl und Kunststoff</p></li>'
 '<li><p>✔hochwertig verarbeitet</p></li>'
 '<li><p>✔gute, langlebige Qualität</p></li>'
 '<li><p>✔mit 4 Rollen, 2 Rollen verfügen über eine Bremse, leicht zu verschieben</p></li>'
 '<li><p>✔variabel an den individuellen Bedarf anpassbar in Höhe und Breite</p></li>'
 '<li><p>✔verstellbare Höhe zwischen 95-170 cm</p></li>'
 '<li><p>✔verstellbare Breite zwischen 86-160 cm</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔Maße: ca. (86-160) x 45 x (95-170) cm (BxTxH)</p></li>'
 '<li><p>✔Material: Edelstahl und Kunststoff</p></li>'
 '<li><p>✔Nettogewicht: 2,2 kg</p></li>'
 '<li><p>✔Belastbarkeit: 25 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Kleiderständer;</p></li></ul>'
 + SPEC + '(86-160)x45x(95-170) cm</p></li>'
 + F + 'Färg:</span> Silber</p></li>'
 + F + 'Material:</span> Edelstahl</p></li>'
 + F + 'Vikt:</span> 2,8 kg</p></li>'
 + F + 'Paketmått:</span> 86 × 8,5 × 17,5 cm</p></li></ul>'
)

K["b0627017"] = (
 '<p>Entdecken Sie den modernen Nachttisch mit Ablagen! Sein minimalistisches Design und die eleganten Weiß- und'
 ' Grautöne verleihen Ihrem Raum einen einzigartigen Look. Mit 4 Rollen ist er mobil und kann mühelos bewegt'
 ' werden. Die zwei Feststellbremsen sorgen für stabilen Halt. Ein flexibler Blickfang für Ihr Zuhause!</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Modernes Design mit eleganter Farbgebung in Grau und Weiß</p></li>'
 '<li><p>verleiht Ihrem Schlafzimmer eine stilvolle Atmosphäre</p></li>'
 '<li><p>✔ 3 Regale bieten reichlich Stauraum für Bücher, Getränke und mehr</p></li>'
 '<li><p>halten Ihr Schlafzimmer ordentlich und organisiert</p></li>'
 '<li><p>✔ 4 360°-Rollen und 2 Feststellbremsen ermöglichen einen einfachen Transport</p></li>'
 '<li><p>erleichtert das Umstellen des Nachtschranks nach Ihren Wünschen</p></li>'
 '<li><p>✔ Solide und stabile Konstruktion aus Holzwerkstoff</p></li>'
 '<li><p>gewährleistet eine zuverlässige und langlebige Nutzung</p></li>'
 '<li><p>✔ Montage erforderlich</p></li>'
 '<li><p>mit leicht verständlicher Anleitung für eine unkomplizierte Aufstellung</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Grau+Weiß</p></li>'
 '<li><p>✔ Material: Spanplatte</p></li>'
 '<li><p>✔ Gesamtmaße: 35L x 29,5B x 65,5H cm</p></li>'
 '<li><p>✔ Größe des mittleren Regals: 19,5L x 29,5B x 1,5H cm</p></li>'
 '<li><p>✔ Höhe unteres Regal: 36 cm</p></li>'
 '<li><p>✔ Tragfähigkeit der Tischplatte: 10 kg</p></li>'
 '<li><p>✔ Tragfähigkeit des Regals: 10 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Nachttisch</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '35L x 29,5B x 65,5H cm</p></li>'
 + F + 'Färg:</span> Grau, Weiß</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 9 kg</p></li>'
 + F + 'Paketmått:</span> 68 × 39 × 13,5 cm</p></li></ul>'
)

K["9c456097"] = (
 '<p>Schaffen Sie eine einladende Atmosphäre mit der Schuhbank aus natürlichem Bambus. Die zwei großzügigen Ablagen'
 ' der Sitzbank bieten Platz für bis zu sechs Paar Schuhe, während die stabile Sitzfläche mit einer Tragkraft von'
 ' 130 kg Komfort und Sicherheit beim Schuheanziehen gewährleistet. Dank des modernen Designs fügt sich die'
 ' Flurbank harmonisch in jeden Raum ein und sorgt für ein entspanntes, ordentliches Zuhause.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Hergestellt aus hochwertigem Bambus, bietet die Schuhbank eine natürliche Ästhetik</p></li>'
 '<li><p>✔ Vielseitiges Design kombiniert Schuhregal und Sitzbank für maximalen Platzgewinn</p></li>'
 '<li><p>✔ Zwei Ablagen bieten Platz für insgesamt 4 Paar Schuhe, ideal für verschiedene Schuhgrößen</p></li>'
 '<li><p>✔ Robuste Konstruktion mit einer Tragfähigkeit von bis zu 136kg für sicheren Gebrauch</p></li>'
 '<li><p>✔ Ergonomisch gestalteter Sitz bietet Komfort beim Schuhewechseln</p></li>'
 '<li><p>✔ Schlichtes natures Design der Flurbank passt zu verschiedenen Einrichtungsstilen und verbessert die'
 ' Raumästhetik</p></li>'
 '<li><p>✔ 5cm Bodenfreiheit der Garderobenbank erleichtert die Reinigung und hält den Boden sauber</p></li>'
 '<li><p>✔ Einfacher Aufbau dank zerlegbarer Struktur, ideal für kleine Wohnungen</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Naturholz</p></li>'
 '<li><p>✔ Material: Bambus</p></li>'
 '<li><p>✔ Gesamtabmessungen: 50L x 28B x 45H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 130 kg (oben), 3 kg (jede Regalebene)</p></li>'
 '<li><p>✔ Geeignet für Schuhgrößen bis maximal 46 (EU)</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Schuhbank</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '50L x 28B x 45H cm</p></li>'
 + F + 'Färg:</span> Naturholz</p></li>'
 + F + 'Material:</span> Bambus</p></li>'
 + F + 'Vikt:</span> 4 kg</p></li>'
 + F + 'Paketmått:</span> 58 × 33,5 × 7,8 cm</p></li></ul>'
)

K["0c07eb82"] = (
 '<p>Richten Sie Ihr Zuhause individuell mit dem anpassbaren Steckregal von ein. Aus robustem Metall gefertigt,'
 ' trägt das Stufenregal bis zu 30 kg und umfasst sechs flexible Würfel, die sich jeder Raumsituation anpassen'
 ' lassen. Die Montage erfolgt sicher mittels ABS-Verbindern. Das offene Design der Würfel erleichtert den Zugriff'
 ' auf Bücher, Spielzeug, Fotos und Kleidung. Halten Sie stilvoll und praktisch Ordnung in Ihrem Zuhause.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Das Set enthält sechs geräumige Würfel, die in beliebiger Form angepasst werden können</p></li>'
 '<li><p>✔ Offenes Design ermöglicht einen einfachen Zugriff auf Ihre Sachen</p></li>'
 '<li><p>✔ Langlebiger und robuster Draht des Regalsystems, der ein Maximum von 30 kg trägt</p></li>'
 '<li><p>✔ ABS-Verbinder des Würfelregals halten die Würfel zusammen und sorgen für Stabilität</p></li>'
 '<li><p>✔ Perfekt für Ihr Zuhause oder das Büro</p></li>'
 '<li><p>✔ Leicht zu reinigen und zu pflegen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Metalldraht</p></li>'
 '<li><p>✔ Gesamtabmessungen: 109L x 37B x 109H cm</p></li>'
 '<li><p>✔ Größe jedes Würfels: 35B x 35T x 35H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 30 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 24 x Metalldraht-Paneel</p></li>'
 '<li><p>✔ 26 x Verbinder</p></li>'
 '<li><p>✔ 1 x Holzhammer</p></li></ul>'
 + SPEC + '109L x 37B x 109H cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 6 kg</p></li>'
 + F + 'Paketmått:</span> 37 × 10 × 43 cm</p></li></ul>'
)


def summa(s):
    h = 0
    for c in s:
        h = (h * 31 + (ord(c) & 0xFFFF)) % 1000000007
    return h


if __name__ == "__main__":
    with io.open("kallor.json", "w", encoding="utf-8") as f:
        json.dump(K, f, ensure_ascii=False, indent=1)
    for k, v in K.items():
        print(k, len(v), summa(v))
