#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bygger rundans kallor.json ur de tyska källtexterna (hämtade server-side
via ExecuteWixAPI mot skarpa V3, ?fields=PLAIN_DESCRIPTION).

☠️ FILEN ÄR EN AVSKRIFT och får därför inte litas på. Kör kontrollen mot
skarpa V3 (samma anrop som ingen skrivning) innan en enda grind körs — samma
ordning som N26–N35. Det är SUMMAN som avgör, inte längden.

Artikelnummer: hämtningen räknade ARTNR-träffar på servern (samma tre
alternativ som gatelib) och fick 0 på alla åtta källtexter, så ingenting är
redigerat här. Kontrollen mot V3 räknar om samma sak i samma anrop.
"""
import io, json, collections

K = collections.OrderedDict()

SPEC = '<h2>Tekniska specifikationer</h2><ul><li><p><span style="font-weight: 700">Mått:</span> '
F = '<li><p><span style="font-weight: 700">'

K["46c0fe07"] = (
 '<p>Wünschen Sie sich auch einen Beistelltisch, der mehr kann als bloß Rumstehen? hat jetzt einen'
 ' Couchtisch auf Rollen, der dank seiner C-Form vielseitig neben oder sogar um Sofa und Bett herum'
 ' positioniert werden kann. Dieser kompakte Tisch ist mit seiner klassischen Kombination aus MDF in'
 ' Walnussoptik und schwarzem Metallrahmen nicht nur schick, sondern steht Ihnen mobil und treu zur'
 ' Seite, egal ob Sie im Bett liegen oder auf dem Sofa sitzen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Stilvoller und multifunktionaler Retro-Couchtisch mit Holzmaserung</p></li>'
 '<li><p>✔ C-Form lässt sich leicht unter Sofas, Sessel oder Bett schieben</p></li>'
 '<li><p>✔ Hergestellt aus robustem MDF und Stahl: strapazierfähig und langlebig</p></li>'
 '<li><p>✔ Tischplatte und untere Gitterablage bieten viel Stauraum für Getränke und Zeitschriften</p></li>'
 '<li><p>✔ Vier Universalrollen: bequem und beweglich</p></li>'
 '<li><p>✔ Melaminierte Oberfläche: wasserdicht und pflegeleicht</p></li>'
 '<li><p>✔ Einfache und schnelle Montage</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Material: MDF, Stahl</p></li>'
 '<li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Gewicht: 5 kg</p></li>'
 '<li><p>✔ Gesamtmaße: L51 x B36 x H65 cm</p></li>'
 '<li><p>✔ Maße Ablage: L50 x B35 cm</p></li>'
 '<li><p>✔ Abstand zwischen Ablage und Tischplatte: 54 cm</p></li>'
 '<li><p>✔ Abstand zwischen Ablage und Boden: 6 cm</p></li>'
 '<li><p>✔ max. Belastbarkeit: 10 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Couchtisch</p></li>'
 '<li><p>✔ 1 x Montageanleitung</p></li></ul>'
 + SPEC + 'L51 x B36 x H65 cm</p></li>'
 + F + 'Färg:</span> Schwarz, Walnuss</p></li>'
 + F + 'Material:</span> Holzwerkstoff/Metall</p></li>'
 + F + 'Vikt:</span> 5,6 kg</p></li>'
 + F + 'Paketmått:</span> 58,5 × 43,5 × 10,5 cm</p></li></ul>'
)

K["3bfee58b"] = (
 '<p>Erleichtern Sie die Bodenreinigung mit dem Mopp-Eimer inklusive Auswringer. Mit einer Kapazität'
 ' von 20 Litern und einer Trennwand, die sauberes von schmutzigem Wasser separiert. Der abnehmbare'
 ' Auswringer presst überschüssiges Wasser aus dem Mopp und ermöglicht ein schnelles, sicheres'
 ' Trocknen. Der Reinigungseimer ist zudem rollbar und lässt sich mühelos bewegen.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ 20-Liter Fassungsvermögen. Trennwand zum Separieren von sauberem und schmutzigem Wasser</p></li>'
 '<li><p>✔ Der Auswringer kann zur leichten Befüllung des Eimers vor der Nutzung entfernt werden</p></li>'
 '<li><p>✔ Vier Räder für müheloses Bewegen</p></li>'
 '<li><p>✔ Robuste Kunststoff-Konstruktion</p></li>'
 '<li><p>✔ Griff zum Anheben und Tragen des Eimers</p></li>'
 '<li><p>✔ Mopp ist nicht enthalten</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz</p></li>'
 '<li><p>✔ Material: Kunststoff</p></li>'
 '<li><p>✔ Gesamtabmessungen: 60L x 27B x 70,5H cm</p></li>'
 '<li><p>✔ Auswringergröße: 24L x 24B x 21,5H cm</p></li>'
 '<li><p>✔ Paneel zum Separieren: 22,5L x 18B cm</p></li>'
 '<li><p>✔ Eimerkapazität: 20 L</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Wischmopp-Eimer mit Auswringer</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '60L x 27B x 70,5H cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Kunststoff/Metall</p></li>'
 + F + 'Vikt:</span> 3,9 kg</p></li>'
 + F + 'Paketmått:</span> 50,5 × 28 × 28,5 cm</p></li></ul>'
)

K["265b0f61"] = (
 '<p>Erleben Sie den Zauber des Striped Wohnzimmer Teppich, ein maschinengefertigtes Meisterstück,'
 ' perfekt für Allergiker und geeignet für Fußbodenheizungen. Das elegante, moderne Design des'
 ' flauschigen Teppichs mit neutralen Streifenmuster macht jeden Bereich, vom Wohnzimmer bis zum Flur,'
 ' stilvoll. Dieser pflegeleichte waschbarer Teppich ist ideal für Haustierbesitzer und bereichert'
 ' jedes Schlaf- oder Esszimmer.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Maschinell getufteter Teppich garantiert Langlebigkeit und Komfort unter den Füßen</p></li>'
 '<li><p>✔ Geeignet der Schlafzimmer Teppich für Allergiker, trägt zu einem gesünderen Zuhause bei</p></li>'
 '<li><p>✔ Kompatibel mit Fußbodenheizung für warme und gemütliche Böden</p></li>'
 '<li><p>✔ Gestreifte geometrische Elemente verleihen eine Note der Eleganz</p></li>'
 '<li><p>✔ Geeignet der Wohnzimmerteppich für Wohnzimmer, Schlafzimmer oder Flure</p></li>'
 '<li><p>✔ Einfach zu reinigen – mit einem heißen Handtuch abwischen oder maschinenwaschbar</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Dunkelgrau</p></li>'
 '<li><p>✔ Material: 100% Polypropylen</p></li>'
 '<li><p>✔ Gesamtabmessungen: 170L x 120B x 1,5H cm</p></li>'
 '<li><p>✔ Florhöhe: 1,4 cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Teppich;</p></li></ul>'
 + SPEC + '170L x 120B x 1,5H cm</p></li>'
 + F + 'Färg:</span> Dunkelgrau</p></li>'
 + F + 'Material:</span> Polypropylen</p></li>'
 + F + 'Vikt:</span> 4,2 kg</p></li>'
 + F + 'Paketmått:</span> 61 × 44 × 11 cm</p></li></ul>'
)

K["69ba5b8b"] = (
 '<p>Entdecken Sie das kreative Talent Ihres Kindes mit der Kindertafel. Diese Kreidetafel Kinder ist'
 ' ideal für Spaß und Inspiration beim Zeichnen und bietet eine beidseitige Tafel für Kreide und'
 ' Trockenlöschmarker, eine anpassbare Höhe sowie praktischen Stauraum für Malutensilien. Aus stabilem'
 ' Holz gefertigt, unterstützt die Tafel Kinder Kreativität und Lernen - perfekt für jedes Spiel- oder'
 ' Klassenzimmer.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Beidseitiges Design für Spaß mit Kreide- und Whiteboard</p></li>'
 '<li><p>✔ Verstellbare Höhe der Tafel Kinder wächst mit Ihrem kleinen Künstler</p></li>'
 '<li><p>✔ Verstellbarer Brettwinkel der Kindertafel für bequeme Zeichenpositionen</p></li>'
 '<li><p>✔ Eingebaute Ablage hält alle Kunstwerkzeuge ordentlich</p></li>'
 '<li><p>✔ Inklusive Papierrolle für endloses kreatives Zeichnen</p></li>'
 '<li><p>✔ Stabiler und robuster Holzrahmen der Kreidetafel Kinder mit glatter Oberfläche</p></li>'
 '<li><p>✔ Fördert Vorstellungskraft, Lernen und die Entwicklung motorischer Fähigkeiten</p></li>'
 '<li><p>✔ Ein tolles Geschenk für junge, kreative Kinder</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Natur</p></li>'
 '<li><p>✔ Material: Kiefernholz, MDF</p></li>'
 '<li><p>✔ Gesamtabmessungen: 48,5L x 46,5B x 70-97H cm</p></li>'
 '<li><p>✔ Zeichenbrett: 32,5L x 43,5B cm</p></li>'
 '<li><p>✔ Tablett: 38L x 39B x 1,5H cm</p></li>'
 '<li><p>✔ Zeichenpapier: 36B x Durchm. 3,5 cm</p></li>'
 '<li><p>✔ Belastbarkeit: 5 kg (Tablett), 5 kg (Zeichenbrett)</p></li>'
 '<li><p>✔ Zugelassenes Alter: ab 3 Jahre</p></li>'
 '<li><p>✔ Empfohlenes Alter: 3-6 Jahre</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Kindermaltisch</p></li>'
 '<li><p>✔ 1 x Bedienungsanleitung</p></li></ul>'
 + SPEC + '48,5cm x 46,5cm x 97cm</p></li>'
 + F + 'Färg:</span> Naturholz</p></li>'
 + F + 'Material:</span> Holzwerkstoff</p></li>'
 + F + 'Vikt:</span> 3,8 kg</p></li>'
 + F + 'Paketmått:</span> 59,5 × 43 × 9,5 cm</p></li></ul>'
)

K["2b27c2a4"] = (
 '<p>Beginnen Sie Ihren Tag mit köstlichem Toast und modernem Stil – dank diesem -Toaster für vier'
 ' Scheiben. Mit wellenförmigem Design, sieben Bräunungsstufen, automatischer Zentrierung und'
 ' Abschaltung genießen Sie perfekten Toast. Die herausnehmbare Krümelschublade erleichtert die'
 ' Reinigung.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Elegantes, schönes geripptes Design sieht großartig auf Ihrer Küchenarbeitsplatte aus</p></li>'
 '<li><p>✔ Aufwärm-, Auftau- und Abbruchfunktion, mit sieben Toaststufen: genießen Sie Ihren Toast so,'
 ' wie Sie ihn mögen</p></li>'
 '<li><p>✔ Hochhub-Design zum einfachen Entfernen kleiner Brotscheiben</p></li>'
 '<li><p>✔ Automatische Brotzentrierung für gleichmäßiges Toasten</p></li>'
 '<li><p>✔ Automatische Abschaltung verhindert Unfälle bei Brotstau oder Überkochen</p></li>'
 '<li><p>✔ Herausnehmbare Krümelschublade für einfache Reinigung</p></li>'
 '<li><p>✔ Vier Schlitze für reichlich Toast</p></li>'
 '<li><p>✔ Mit energiesparender ERP-Zertifizierung, keine Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Grau</p></li>'
 '<li><p>✔ Material: Kunststoff, Stahl</p></li>'
 '<li><p>✔ Gesamtabmessungen: 29,2L x 27,5B x 18,9H cm</p></li>'
 '<li><p>✔ Größe jedes Fachs: 13,5L x 3,5B x 13,5H cm</p></li>'
 '<li><p>✔ Eingang: 220-240V 50/60Hz</p></li>'
 '<li><p>✔ Ausgang: 1560-1860W 7,8A</p></li>'
 '<li><p>✔ Kabellänge: 0,7 m</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Toaster</p></li>'
 '<li><p>✔ 1 x Handbuch</p></li></ul>'
 + SPEC + '29,2cm x 27,5cm x 18,9cm</p></li>'
 + F + 'Färg:</span> Grau</p></li>'
 + F + 'Material:</span> Kunststoff/Edelstahl</p></li>'
 + F + 'Vikt:</span> 2,2 kg</p></li>'
 + F + 'Paketmått:</span> 33,4 × 33,4 × 23,5 cm</p></li></ul>'
)

K["37804a40"] = (
 '<p>Verstauen Sie Ihre Kleidung mühelos mit dem innovativen DIY-Kleiderschrank von . Aus'
 ' strapazierfähigem Kunststoff gefertigt, bietet er ein flexibles Design mit zwei großen und neun'
 ' kleineren Würfeln, die sich beliebig zusammenfügen lassen. Ideal angepasst für jeden Raum, sorgt der'
 ' Metallrahmen in jedem Würfel für Stabilität und trägt bis zu 30 kg. Die Montage und Demontage ist'
 ' zudem kinderleicht und schnell erledigt.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Selbstmontierbarer Kleiderschrank, der mit den mitgelieferten ABS-Verbindern in jede Form'
 ' gebracht werden kann</p></li>'
 '<li><p>✔ Strapazierfähige Plastikwürfel mit einem Metallrahmen für zusätzliche Unterstützung</p></li>'
 '<li><p>✔ Zwei Kleiderstangen</p></li>'
 '<li><p>✔ Zwei große und neun kleine Würfel für viel Stauraum</p></li>'
 '<li><p>✔ Leicht zu reinigen und zu pflegen</p></li>'
 '<li><p>✔ Türen mit Metallring zum einfachen Öffnen und Schließen</p></li>'
 '<li><p>✔ Auch hervorragend für die Aufbewahrung anderer Gegenstände geeignet</p></li>'
 '<li><p>✔ Maximale Gewichtskapazität: 30 kg</p></li></ul>'
 '<h3>Technische Daten:</h3><ul><li><p>✔ Farbe: Schwarz+Weiß</p></li>'
 '<li><p>✔ Material: Kunststoff, Metalldraht</p></li>'
 '<li><p>✔ Gesamtabmessungen: 111L x 47B x 183H cm</p></li>'
 '<li><p>✔ 9 x Kleine Würfelgröße: 35B x 45T x 35H cm</p></li>'
 '<li><p>✔ 2 x Große Würfelgröße: 35B x 45T x 105H cm</p></li>'
 '<li><p>✔ Belastbarkeit: 30 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 49 x schwarze Platte</p></li>'
 '<li><p>✔ 15 x weiße Platte</p></li>'
 '<li><p>✔ 48 x Verbinder</p></li>'
 '<li><p>✔ 4 x Kabelbinder</p></li>'
 '<li><p>✔ 2 x Kleiderstange</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li>'
 '<li><p>✔ 1 x Holzhammer</p></li></ul>'
 + SPEC + 'B111 x T47 x H183 cm</p></li>'
 + F + 'Färg:</span> Schwarz</p></li>'
 + F + 'Material:</span> Kunststoff</p></li>'
 + F + 'Vikt:</span> 12,5 kg</p></li>'
 + F + 'Paketmått:</span> 38 × 25 × 48 cm</p></li></ul>'
)

K["6707c9dd"] = (
 '<p>Mit den hübschen Aufbewahrungsboxen von wird das Ordnunghalten zum Vergnügen! Das kindgerechte'
 ' Design mit abgerundeten Kanten sorgt für Sicherheit und Spaß zugleich. Drei geräumige Schubladen'
 ' bieten viel Platz für Spielzeug, Kleidung, Kissen und andere Dinge. So wird das Aufräumen zum'
 ' Kinderspiel. Bringen Sie Freude und Ordnung ins Kinderzimmer – mit den praktischen'
 ' Aufbewahrungsboxen von !</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Drei große Schubladen und eine breite Fläche bieten großzügigen Stauraum für Spielzeug,'
 ' Kleidung, Puppen, Kissen und mehr</p></li>'
 '<li><p>✔ Runde Polierkante verhindert, dass sich Ihr Kind verletzt</p></li>'
 '<li><p>✔ Blaue Farbtöne machen die Aufbewahrungsboxen zu einer tollen Dekoration für das'
 ' Kinderzimmer</p></li>'
 '<li><p>✔ Das erhöhte Design schützt vor Feuchtigkeit von unten</p></li>'
 '<li><p>✔ Ideal für Schlafzimmer, Kinderzimmer, Kindergarten oder Wohnzimmer – überall, wo'
 ' zusätzlicher Platz benötigt wird</p></li>'
 '<li><p>✔ Einfaches und kindgerechtes Design zum Herausziehen</p></li>'
 '<li><p>✔ Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Blau</p></li>'
 '<li><p>✔ Material: Kunststoff</p></li>'
 '<li><p>✔ Gesamtmaße: 37L x 37B x 56,5H cm</p></li>'
 '<li><p>✔ Schubladengröße (Innenraum): 33L x 31,5B x 15H cm</p></li>'
 '<li><p>✔ Höhe der Füße: 2,5 cm</p></li>'
 '<li><p>✔ Belastbarkeit (jede Ebene): 10 kg</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Aufbewahrungsbox</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '37L x 37B x 56,5H cm</p></li>'
 + F + 'Färg:</span> Blau</p></li>'
 + F + 'Material:</span> Kunststoff</p></li>'
 + F + 'Vikt:</span> 5,3 kg</p></li>'
 + F + 'Paketmått:</span> 39 × 39 × 38 cm</p></li></ul>'
)

K["676e567f"] = (
 '<p>Postzustellungen sollten Ihren Frieden nicht stören oder Ihre Veranda unordentlich hinterlassen.'
 ' Der -Briefkasten löst dieses Problem mit einem leise schließenden Deckel und separatem'
 ' Zeitungshalter. Dieser moderne Briefkasten mit Sichtfenster sorgt für Ordnung im Eingangsbereich'
 ' und macht das Abholen der Post angenehm und mühelos.</p>'
 '<h3>Beschreibung:</h3><ul>'
 '<li><p>✔ Dieser moderne Briefkasten verfügt über ein schlankes geometrisches Design für stilvolle'
 ' Eingangsbereiche</p></li>'
 '<li><p>✔ Eingebaute schalldämmende Pads sorgen dafür, dass der Deckel sanft und geräuschlos'
 ' schließt</p></li>'
 '<li><p>✔ Ein großes 13-Liter-Fach und ein separater Zeitungsrollenhalter halten die Post'
 ' organisiert</p></li>'
 '<li><p>✔ Das Schloss des Wandbriefkastens mit zwei Schlüsseln bietet hervorragende Sicherheit für'
 ' Ihre Post</p></li>'
 '<li><p>✔ Die Entwässerungslöcher schützen den Inhalt vor verschiedenen Wetterbedingungen</p></li>'
 '<li><p>✔ Unser wandmontierter Briefkasten lässt sich einfach mit dem mitgelieferten Montagematerial'
 ' installieren</p></li>'
 '<li><p>✔ Keine Montage erforderlich</p></li></ul>'
 '<h3> Technische Daten:</h3><ul><li><p>✔ Farbe: Dunkelgrau+Silber</p></li>'
 '<li><p>✔ Material: Metall, Edelstahl, Kupfer</p></li>'
 '<li><p>✔ Gesamtabmessungen: 37L x 10B x 37H cm</p></li>'
 '<li><p>✔ Innenmaße: 36L x 9B x 26H cm</p></li>'
 '<li><p>✔ Türgröße: 37B x 26H cm</p></li>'
 '<li><p>✔ Briefschlitzgröße: 34L x 3B cm</p></li>'
 '<li><p>✔ Belastbarkeit: 10 kg</p></li>'
 '<li><p>✔ Größe der Briefzugangsöffnung: 34B x 23H cm</p></li></ul>'
 '<h3>Lieferumfang:</h3><ul><li><p>✔ 1 x Briefkasten</p></li>'
 '<li><p>✔ 2 x Schlüssel</p></li>'
 '<li><p>✔ 1 x Anleitung</p></li></ul>'
 + SPEC + '37cm x 10cm x 37cm</p></li>'
 + F + 'Färg:</span> Dunkelgrau</p></li>'
 + F + 'Material:</span> Metall</p></li>'
 + F + 'Vikt:</span> 4 kg</p></li>'
 + F + 'Paketmått:</span> 42 × 21 × 48 cm</p></li></ul>'
)

if __name__ == "__main__":
    json.dump(K, io.open("kallor.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    for kort, html in K.items():
        print(f"{kort}\t{len(html)} tecken")
